/* Auto-generated from the `curriculum` table. Do not hand-edit topic ids/titles here;
   regenerate instead. Content for each lesson lives in lessons/all-ml-content.js. */
window.ALLML_SECTION = "All ML";
window.ALLML_PARTS = [
  { num: 1, name: "Statistical Learning Theory" },
  { num: 2, name: "Optimization" },
  { num: 3, name: "Core Machine Learning" },
  { num: 4, name: "Unsupervised Learning" },
  { num: 5, name: "Probabilistic & Graphical Models" },
  { num: 6, name: "Deep Learning Foundations" },
  { num: 7, name: "Computer Vision" },
  { num: 8, name: "Sequence Models & NLP" },
  { num: 9, name: "Large Language Models" },
  { num: 10, name: "Generative Models" },
  { num: 11, name: "Reinforcement Learning" },
  { num: 12, name: "Graph & Geometric Learning" },
  { num: 13, name: "Speech & Audio" },
  { num: 14, name: "Time Series & Forecasting" },
  { num: 15, name: "Recommender Systems & Ranking" },
  { num: 16, name: "Information Retrieval & Search" },
  { num: 17, name: "Learning Paradigms" },
  { num: 18, name: "Data-Centric AI" },
  { num: 19, name: "Trustworthy, Responsible & Robust AI" },
  { num: 20, name: "ML Systems, MLOps & Production" },
  { num: 21, name: "Classical / Symbolic AI" },
  { num: 22, name: "Search & Planning" },
  { num: 23, name: "Game Theory & Multi-Agent Systems" },
  { num: 24, name: "Evolutionary Computation & Swarm Intelligence" },
  { num: 25, name: "Neurosymbolic AI & Program Synthesis" },
  { num: 27, name: "Frontiers" },
];
window.ALLML = window.ALLML || [];
window.ALLML.push({"id": "1.1", "part": 1, "title": "Empirical Risk Minimization", "gap": false});
window.ALLML.push({"id": "1.2", "part": 1, "title": "The bias–complexity tradeoff", "gap": false});
window.ALLML.push({"id": "1.3", "part": 1, "title": "PAC learning", "gap": true});
window.ALLML.push({"id": "1.4", "part": 1, "title": "VC dimension", "gap": false});
window.ALLML.push({"id": "1.5", "part": 1, "title": "Rademacher complexity", "gap": false});
window.ALLML.push({"id": "1.6", "part": 1, "title": "Generalization bounds", "gap": false});
window.ALLML.push({"id": "1.7", "part": 1, "title": "Structural Risk Minimization", "gap": false});
window.ALLML.push({"id": "1.8", "part": 1, "title": "Regularization theory", "gap": false});
window.ALLML.push({"id": "1.9", "part": 1, "title": "Algorithmic stability", "gap": false});
window.ALLML.push({"id": "1.10", "part": 1, "title": "The No Free Lunch theorem", "gap": false});
window.ALLML.push({"id": "1.11", "part": 1, "title": "Uniform convergence", "gap": false});
window.ALLML.push({"id": "2.1", "part": 2, "title": "Convex sets & convex functions", "gap": false});
window.ALLML.push({"id": "2.2", "part": 2, "title": "Unconstrained optimization & optimality conditions", "gap": false});
window.ALLML.push({"id": "2.3", "part": 2, "title": "Gradient descent (foundations)", "gap": false});
window.ALLML.push({"id": "2.4", "part": 2, "title": "Line search & trust regions", "gap": false});
window.ALLML.push({"id": "2.5", "part": 2, "title": "Newton & quasi-Newton methods (BFGS, L-BFGS)", "gap": false});
window.ALLML.push({"id": "2.6", "part": 2, "title": "Conjugate gradient", "gap": false});
window.ALLML.push({"id": "2.7", "part": 2, "title": "Coordinate descent", "gap": false});
window.ALLML.push({"id": "2.8", "part": 2, "title": "Proximal & subgradient methods", "gap": false});
window.ALLML.push({"id": "2.9", "part": 2, "title": "Constrained optimization, Lagrange multipliers, KKT", "gap": false});
window.ALLML.push({"id": "2.10", "part": 2, "title": "Duality (Lagrangian & Wolfe)", "gap": false});
window.ALLML.push({"id": "2.11", "part": 2, "title": "Stochastic optimization theory", "gap": false});
window.ALLML.push({"id": "2.12", "part": 2, "title": "Linear & quadratic programming", "gap": false});
window.ALLML.push({"id": "2.13", "part": 2, "title": "Integer & combinatorial optimization", "gap": false});
window.ALLML.push({"id": "2.14", "part": 2, "title": "Bayesian optimization", "gap": false});
window.ALLML.push({"id": "2.15", "part": 2, "title": "Black-box & derivative-free optimization", "gap": false});
window.ALLML.push({"id": "2.16", "part": 2, "title": "Simulated annealing & tabu search", "gap": false});
window.ALLML.push({"id": "3.1", "part": 3, "title": "ML framing (supervised/unsupervised/semi/self)", "gap": false});
window.ALLML.push({"id": "3.2", "part": 3, "title": "Generalization & the i.i.d. assumption", "gap": false});
window.ALLML.push({"id": "3.3", "part": 3, "title": "The bias–variance tradeoff", "gap": false});
window.ALLML.push({"id": "3.4", "part": 3, "title": "The perceptron algorithm", "gap": false});
window.ALLML.push({"id": "3.5", "part": 3, "title": "Linear regression (OLS & normal equation)", "gap": false});
window.ALLML.push({"id": "3.6", "part": 3, "title": "Linear regression via gradient descent", "gap": false});
window.ALLML.push({"id": "3.7", "part": 3, "title": "Polynomial & basis-function regression", "gap": false});
window.ALLML.push({"id": "3.8", "part": 3, "title": "Ridge regression (L2)", "gap": false});
window.ALLML.push({"id": "3.9", "part": 3, "title": "Lasso (L1) & sparsity", "gap": false});
window.ALLML.push({"id": "3.10", "part": 3, "title": "Elastic Net", "gap": true});
window.ALLML.push({"id": "3.11", "part": 3, "title": "Kernel ridge regression", "gap": false});
window.ALLML.push({"id": "3.12", "part": 3, "title": "Quantile & isotonic regression", "gap": true});
window.ALLML.push({"id": "3.13", "part": 3, "title": "Robust regression (Huber, RANSAC)", "gap": false});
window.ALLML.push({"id": "3.14", "part": 3, "title": "Logistic regression", "gap": false});
window.ALLML.push({"id": "3.15", "part": 3, "title": "Softmax / multinomial regression", "gap": false});
window.ALLML.push({"id": "3.16", "part": 3, "title": "Generalized Linear Models", "gap": false});
window.ALLML.push({"id": "3.17", "part": 3, "title": "Linear & Quadratic Discriminant Analysis", "gap": false});
window.ALLML.push({"id": "3.18", "part": 3, "title": "Gaussian Discriminant Analysis", "gap": false});
window.ALLML.push({"id": "3.19", "part": 3, "title": "Gradient descent variants (batch, mini-batch, SGD)", "gap": false});
window.ALLML.push({"id": "3.20", "part": 3, "title": "k-Nearest Neighbors", "gap": false});
window.ALLML.push({"id": "3.21", "part": 3, "title": "Naive Bayes", "gap": false});
window.ALLML.push({"id": "3.22", "part": 3, "title": "Decision trees (CART, entropy/Gini, pruning)", "gap": false});
window.ALLML.push({"id": "3.23", "part": 3, "title": "Bagging & Random Forests", "gap": false});
window.ALLML.push({"id": "3.24", "part": 3, "title": "Extremely Randomized Trees", "gap": false});
window.ALLML.push({"id": "3.25", "part": 3, "title": "AdaBoost", "gap": false});
window.ALLML.push({"id": "3.26", "part": 3, "title": "Gradient Boosting Machines", "gap": false});
window.ALLML.push({"id": "3.27", "part": 3, "title": "XGBoost / LightGBM / CatBoost", "gap": false});
window.ALLML.push({"id": "3.28", "part": 3, "title": "Stacking & blending", "gap": false});
window.ALLML.push({"id": "3.29", "part": 3, "title": "Support Vector Machines & margins", "gap": false});
window.ALLML.push({"id": "3.30", "part": 3, "title": "The kernel trick & kernel methods", "gap": false});
window.ALLML.push({"id": "3.31", "part": 3, "title": "Online & incremental learning", "gap": false});
window.ALLML.push({"id": "3.32", "part": 3, "title": "Passive-aggressive algorithms", "gap": true});
window.ALLML.push({"id": "3.33", "part": 3, "title": "Ordinal & multi-output regression", "gap": false});
window.ALLML.push({"id": "3.34", "part": 3, "title": "Survival analysis (Cox proportional hazards)", "gap": false});
window.ALLML.push({"id": "3.35", "part": 3, "title": "Cost-sensitive learning", "gap": false});
window.ALLML.push({"id": "3.36", "part": 3, "title": "Train/validation/test & cross-validation", "gap": false});
window.ALLML.push({"id": "3.37", "part": 3, "title": "Nested cross-validation", "gap": false});
window.ALLML.push({"id": "3.38", "part": 3, "title": "Classification metrics (precision, recall, F1, ROC/AUC, PR)", "gap": false});
window.ALLML.push({"id": "3.39", "part": 3, "title": "Regression metrics (MSE, MAE, R²)", "gap": false});
window.ALLML.push({"id": "3.40", "part": 3, "title": "Probability calibration", "gap": false});
window.ALLML.push({"id": "3.41", "part": 3, "title": "Model selection (AIC, BIC, MDL)", "gap": false});
window.ALLML.push({"id": "3.42", "part": 3, "title": "Overfitting, underfitting & learning curves", "gap": false});
window.ALLML.push({"id": "3.43", "part": 3, "title": "Data leakage", "gap": false});
window.ALLML.push({"id": "3.44", "part": 3, "title": "Hyperparameter search (grid, random, Bayesian, Hyperband)", "gap": false});
window.ALLML.push({"id": "3.45", "part": 3, "title": "Feature engineering", "gap": false});
window.ALLML.push({"id": "3.46", "part": 3, "title": "Feature selection (filter, wrapper, embedded)", "gap": false});
window.ALLML.push({"id": "3.47", "part": 3, "title": "Imbalanced data (resampling, SMOTE, class weights)", "gap": false});
window.ALLML.push({"id": "3.48", "part": 3, "title": "Multiclass & multilabel strategies", "gap": false});
window.ALLML.push({"id": "4.1", "part": 4, "title": "k-means & k-means++", "gap": false});
window.ALLML.push({"id": "4.2", "part": 4, "title": "Mean-shift clustering", "gap": false});
window.ALLML.push({"id": "4.3", "part": 4, "title": "Affinity propagation", "gap": false});
window.ALLML.push({"id": "4.4", "part": 4, "title": "Hierarchical / agglomerative clustering", "gap": false});
window.ALLML.push({"id": "4.5", "part": 4, "title": "DBSCAN, OPTICS & HDBSCAN", "gap": false});
window.ALLML.push({"id": "4.6", "part": 4, "title": "BIRCH", "gap": true});
window.ALLML.push({"id": "4.7", "part": 4, "title": "Fuzzy c-means", "gap": false});
window.ALLML.push({"id": "4.8", "part": 4, "title": "Gaussian Mixture Models & EM", "gap": false});
window.ALLML.push({"id": "4.9", "part": 4, "title": "Spectral clustering", "gap": false});
window.ALLML.push({"id": "4.10", "part": 4, "title": "Self-Organizing Maps", "gap": false});
window.ALLML.push({"id": "4.11", "part": 4, "title": "Cluster evaluation (silhouette, Davies–Bouldin, ARI)", "gap": false});
window.ALLML.push({"id": "4.12", "part": 4, "title": "Principal Component Analysis", "gap": false});
window.ALLML.push({"id": "4.13", "part": 4, "title": "Truncated SVD / Latent Semantic Analysis", "gap": false});
window.ALLML.push({"id": "4.14", "part": 4, "title": "Kernel PCA", "gap": false});
window.ALLML.push({"id": "4.15", "part": 4, "title": "Independent Component Analysis", "gap": false});
window.ALLML.push({"id": "4.16", "part": 4, "title": "Factor analysis", "gap": false});
window.ALLML.push({"id": "4.17", "part": 4, "title": "Dictionary learning & sparse coding", "gap": false});
window.ALLML.push({"id": "4.18", "part": 4, "title": "Random projections", "gap": false});
window.ALLML.push({"id": "4.19", "part": 4, "title": "t-SNE", "gap": false});
window.ALLML.push({"id": "4.20", "part": 4, "title": "UMAP", "gap": false});
window.ALLML.push({"id": "4.21", "part": 4, "title": "Manifold learning (Isomap, LLE, MDS, Laplacian eigenmaps)", "gap": false});
window.ALLML.push({"id": "4.22", "part": 4, "title": "Non-negative Matrix Factorization", "gap": false});
window.ALLML.push({"id": "4.23", "part": 4, "title": "Biclustering / co-clustering", "gap": false});
window.ALLML.push({"id": "4.24", "part": 4, "title": "Anomaly & outlier detection (Isolation Forest, One-Class SVM, LOF)", "gap": false});
window.ALLML.push({"id": "4.25", "part": 4, "title": "Kernel Density Estimation", "gap": false});
window.ALLML.push({"id": "4.26", "part": 4, "title": "Association rule mining (Apriori, FP-growth)", "gap": false});
window.ALLML.push({"id": "5.1", "part": 5, "title": "Bayesian inference foundations", "gap": false});
window.ALLML.push({"id": "5.2", "part": 5, "title": "Bayesian linear & logistic regression", "gap": false});
window.ALLML.push({"id": "5.3", "part": 5, "title": "Bayesian networks (directed models)", "gap": false});
window.ALLML.push({"id": "5.4", "part": 5, "title": "Markov random fields (undirected models)", "gap": false});
window.ALLML.push({"id": "5.5", "part": 5, "title": "Factor graphs", "gap": false});
window.ALLML.push({"id": "5.6", "part": 5, "title": "Belief propagation (sum-product, max-product)", "gap": false});
window.ALLML.push({"id": "5.7", "part": 5, "title": "The junction-tree algorithm", "gap": false});
window.ALLML.push({"id": "5.8", "part": 5, "title": "Structure learning", "gap": false});
window.ALLML.push({"id": "5.9", "part": 5, "title": "Hidden Markov Models", "gap": false});
window.ALLML.push({"id": "5.10", "part": 5, "title": "Conditional Random Fields", "gap": false});
window.ALLML.push({"id": "5.11", "part": 5, "title": "Kalman filters", "gap": false});
window.ALLML.push({"id": "5.12", "part": 5, "title": "Particle filters", "gap": false});
window.ALLML.push({"id": "5.13", "part": 5, "title": "Dynamic Bayesian networks", "gap": false});
window.ALLML.push({"id": "5.14", "part": 5, "title": "Gaussian Processes", "gap": false});
window.ALLML.push({"id": "5.15", "part": 5, "title": "The EM algorithm (general)", "gap": false});
window.ALLML.push({"id": "5.16", "part": 5, "title": "Variational inference", "gap": false});
window.ALLML.push({"id": "5.17", "part": 5, "title": "Stochastic variational inference", "gap": false});
window.ALLML.push({"id": "5.18", "part": 5, "title": "Expectation propagation", "gap": false});
window.ALLML.push({"id": "5.19", "part": 5, "title": "Sampling (rejection, importance)", "gap": false});
window.ALLML.push({"id": "5.20", "part": 5, "title": "MCMC: Metropolis–Hastings & Gibbs", "gap": false});
window.ALLML.push({"id": "5.21", "part": 5, "title": "Hamiltonian Monte Carlo & NUTS", "gap": false});
window.ALLML.push({"id": "5.22", "part": 5, "title": "Nonparametric Bayes & Dirichlet processes", "gap": false});
window.ALLML.push({"id": "5.23", "part": 5, "title": "Latent Dirichlet Allocation & topic models", "gap": false});
window.ALLML.push({"id": "5.24", "part": 5, "title": "Probabilistic programming", "gap": false});
window.ALLML.push({"id": "6.1", "part": 6, "title": "The perceptron & MLPs", "gap": false});
window.ALLML.push({"id": "6.2", "part": 6, "title": "The universal approximation theorem", "gap": false});
window.ALLML.push({"id": "6.3", "part": 6, "title": "Activation functions (sigmoid, tanh, ReLU, GELU, softmax)", "gap": false});
window.ALLML.push({"id": "6.4", "part": 6, "title": "Backpropagation", "gap": false});
window.ALLML.push({"id": "6.5", "part": 6, "title": "Automatic differentiation & computational graphs", "gap": false});
window.ALLML.push({"id": "6.6", "part": 6, "title": "Loss functions (MSE, cross-entropy, hinge, contrastive, triplet)", "gap": false});
window.ALLML.push({"id": "6.7", "part": 6, "title": "SGD, Momentum, Nesterov", "gap": false});
window.ALLML.push({"id": "6.8", "part": 6, "title": "AdaGrad, RMSProp, Adam, AdamW", "gap": false});
window.ALLML.push({"id": "6.9", "part": 6, "title": "Lion, LAMB & large-batch optimizers", "gap": false});
window.ALLML.push({"id": "6.10", "part": 6, "title": "Second-order methods for DL (K-FAC)", "gap": false});
window.ALLML.push({"id": "6.11", "part": 6, "title": "Weight initialization (Xavier, He, orthogonal, LSUV)", "gap": false});
window.ALLML.push({"id": "6.12", "part": 6, "title": "Dropout & DropConnect", "gap": false});
window.ALLML.push({"id": "6.13", "part": 6, "title": "Weight decay & early stopping", "gap": false});
window.ALLML.push({"id": "6.14", "part": 6, "title": "Label smoothing", "gap": false});
window.ALLML.push({"id": "6.15", "part": 6, "title": "Batch normalization", "gap": false});
window.ALLML.push({"id": "6.16", "part": 6, "title": "Layer / group / instance normalization", "gap": false});
window.ALLML.push({"id": "6.17", "part": 6, "title": "Residual & skip connections", "gap": false});
window.ALLML.push({"id": "6.18", "part": 6, "title": "Vanishing & exploding gradients", "gap": false});
window.ALLML.push({"id": "6.19", "part": 6, "title": "Gradient clipping", "gap": false});
window.ALLML.push({"id": "6.20", "part": 6, "title": "Learning-rate schedules (step, cosine, warmup, one-cycle)", "gap": false});
window.ALLML.push({"id": "6.21", "part": 6, "title": "Gradient checking", "gap": false});
window.ALLML.push({"id": "6.22", "part": 6, "title": "Gradient accumulation & activation checkpointing", "gap": false});
window.ALLML.push({"id": "6.23", "part": 6, "title": "Stochastic depth & spectral normalization", "gap": false});
window.ALLML.push({"id": "6.24", "part": 6, "title": "Transfer learning & fine-tuning", "gap": false});
window.ALLML.push({"id": "6.25", "part": 6, "title": "Data augmentation", "gap": false});
window.ALLML.push({"id": "6.26", "part": 6, "title": "Mixture-of-Experts layers", "gap": false});
window.ALLML.push({"id": "6.27", "part": 6, "title": "Neural ODEs", "gap": false});
window.ALLML.push({"id": "6.28", "part": 6, "title": "Hypernetworks", "gap": true});
window.ALLML.push({"id": "6.29", "part": 6, "title": "Capsule networks", "gap": true});
window.ALLML.push({"id": "6.30", "part": 6, "title": "Spiking neural networks", "gap": true});
window.ALLML.push({"id": "6.31", "part": 6, "title": "Neural Architecture Search", "gap": false});
window.ALLML.push({"id": "6.32", "part": 6, "title": "The lottery-ticket hypothesis", "gap": false});
window.ALLML.push({"id": "6.33", "part": 6, "title": "Double descent & grokking", "gap": false});
window.ALLML.push({"id": "6.34", "part": 6, "title": "Hardware (GPU/TPU) & mixed-precision training", "gap": false});
window.ALLML.push({"id": "7.1", "part": 7, "title": "Image representation & color spaces", "gap": false});
window.ALLML.push({"id": "7.2", "part": 7, "title": "Classical features (SIFT, HOG, edges, Hough)", "gap": false});
window.ALLML.push({"id": "7.3", "part": 7, "title": "The convolution operation", "gap": false});
window.ALLML.push({"id": "7.4", "part": 7, "title": "CNN building blocks (stride, padding, pooling)", "gap": false});
window.ALLML.push({"id": "7.5", "part": 7, "title": "Transposed & dilated convolutions", "gap": false});
window.ALLML.push({"id": "7.6", "part": 7, "title": "Depthwise-separable convolutions (MobileNet)", "gap": false});
window.ALLML.push({"id": "7.7", "part": 7, "title": "Squeeze-and-Excitation blocks", "gap": false});
window.ALLML.push({"id": "7.8", "part": 7, "title": "LeNet & AlexNet", "gap": false});
window.ALLML.push({"id": "7.9", "part": 7, "title": "VGG & Inception", "gap": false});
window.ALLML.push({"id": "7.10", "part": 7, "title": "ResNet & residual learning", "gap": false});
window.ALLML.push({"id": "7.11", "part": 7, "title": "DenseNet & EfficientNet", "gap": false});
window.ALLML.push({"id": "7.12", "part": 7, "title": "ConvNeXt", "gap": false});
window.ALLML.push({"id": "7.13", "part": 7, "title": "Anchors, IoU, NMS & mAP", "gap": false});
window.ALLML.push({"id": "7.14", "part": 7, "title": "Object detection: R-CNN family", "gap": false});
window.ALLML.push({"id": "7.15", "part": 7, "title": "Object detection: YOLO & SSD", "gap": false});
window.ALLML.push({"id": "7.16", "part": 7, "title": "Feature Pyramid Networks & RetinaNet", "gap": false});
window.ALLML.push({"id": "7.17", "part": 7, "title": "Object detection: DETR", "gap": false});
window.ALLML.push({"id": "7.18", "part": 7, "title": "Semantic segmentation (FCN, U-Net)", "gap": false});
window.ALLML.push({"id": "7.19", "part": 7, "title": "Instance & panoptic segmentation (Mask R-CNN)", "gap": false});
window.ALLML.push({"id": "7.20", "part": 7, "title": "Vision Transformers (ViT)", "gap": false});
window.ALLML.push({"id": "7.21", "part": 7, "title": "Swin Transformer", "gap": false});
window.ALLML.push({"id": "7.22", "part": 7, "title": "Self-supervised vision (MAE, DINO, SimCLR)", "gap": false});
window.ALLML.push({"id": "7.23", "part": 7, "title": "Image captioning", "gap": false});
window.ALLML.push({"id": "7.24", "part": 7, "title": "Super-resolution", "gap": false});
window.ALLML.push({"id": "7.25", "part": 7, "title": "Optical flow", "gap": false});
window.ALLML.push({"id": "7.26", "part": 7, "title": "Pose estimation & keypoints", "gap": false});
window.ALLML.push({"id": "7.27", "part": 7, "title": "OCR & scene text", "gap": false});
window.ALLML.push({"id": "7.28", "part": 7, "title": "Face recognition & metric learning", "gap": false});
window.ALLML.push({"id": "7.29", "part": 7, "title": "Video understanding & action recognition", "gap": false});
window.ALLML.push({"id": "7.30", "part": 7, "title": "3D vision & point clouds (PointNet)", "gap": false});
window.ALLML.push({"id": "7.31", "part": 7, "title": "Neural rendering & NeRF", "gap": true});
window.ALLML.push({"id": "8.1", "part": 8, "title": "Text preprocessing & normalization", "gap": false});
window.ALLML.push({"id": "8.2", "part": 8, "title": "Edit distance & string algorithms", "gap": false});
window.ALLML.push({"id": "8.3", "part": 8, "title": "Tokenization (BPE, WordPiece, SentencePiece)", "gap": false});
window.ALLML.push({"id": "8.4", "part": 8, "title": "Bag-of-words & TF-IDF", "gap": false});
window.ALLML.push({"id": "8.5", "part": 8, "title": "n-gram language models", "gap": false});
window.ALLML.push({"id": "8.6", "part": 8, "title": "Word embeddings (Word2Vec, GloVe, FastText)", "gap": false});
window.ALLML.push({"id": "8.7", "part": 8, "title": "Recurrent Neural Networks", "gap": false});
window.ALLML.push({"id": "8.8", "part": 8, "title": "LSTM", "gap": false});
window.ALLML.push({"id": "8.9", "part": 8, "title": "GRU", "gap": false});
window.ALLML.push({"id": "8.10", "part": 8, "title": "Sequence-to-sequence (encoder–decoder)", "gap": false});
window.ALLML.push({"id": "8.11", "part": 8, "title": "Attention mechanism", "gap": false});
window.ALLML.push({"id": "8.12", "part": 8, "title": "Transformers (self-attention, multi-head)", "gap": false});
window.ALLML.push({"id": "8.13", "part": 8, "title": "Positional encodings (sinusoidal, learned, RoPE, ALiBi, relative)", "gap": false});
window.ALLML.push({"id": "8.14", "part": 8, "title": "Efficient & long-context attention (Longformer, BigBird, FlashAttention)", "gap": false});
window.ALLML.push({"id": "8.15", "part": 8, "title": "Decoding strategies (greedy, beam, top-k, nucleus, temperature)", "gap": false});
window.ALLML.push({"id": "8.16", "part": 8, "title": "Language-model evaluation (perplexity, BLEU, ROUGE, METEOR)", "gap": false});
window.ALLML.push({"id": "8.17", "part": 8, "title": "Named entity recognition & sequence labeling", "gap": false});
window.ALLML.push({"id": "8.18", "part": 8, "title": "POS tagging & morphology", "gap": true});
window.ALLML.push({"id": "8.19", "part": 8, "title": "Dependency & constituency parsing", "gap": false});
window.ALLML.push({"id": "8.20", "part": 8, "title": "Coreference resolution", "gap": false});
window.ALLML.push({"id": "8.21", "part": 8, "title": "Semantic role labeling", "gap": false});
window.ALLML.push({"id": "8.22", "part": 8, "title": "Machine translation", "gap": false});
window.ALLML.push({"id": "8.23", "part": 8, "title": "Question answering", "gap": false});
window.ALLML.push({"id": "8.24", "part": 8, "title": "Summarization", "gap": true});
window.ALLML.push({"id": "8.25", "part": 8, "title": "Text classification & sentiment", "gap": false});
window.ALLML.push({"id": "8.26", "part": 8, "title": "Dialogue systems & chatbots", "gap": false});
window.ALLML.push({"id": "8.27", "part": 8, "title": "Multilingual & cross-lingual NLP", "gap": false});
window.ALLML.push({"id": "8.28", "part": 8, "title": "Text-to-SQL & semantic parsing", "gap": false});
window.ALLML.push({"id": "9.1", "part": 9, "title": "Encoder-only models (BERT & variants)", "gap": false});
window.ALLML.push({"id": "9.2", "part": 9, "title": "Decoder-only models (GPT family)", "gap": false});
window.ALLML.push({"id": "9.3", "part": 9, "title": "Encoder–decoder models (T5, BART)", "gap": false});
window.ALLML.push({"id": "9.4", "part": 9, "title": "Pretraining objectives (MLM, next-token, denoising)", "gap": false});
window.ALLML.push({"id": "9.5", "part": 9, "title": "Scaling laws & emergent abilities", "gap": false});
window.ALLML.push({"id": "9.6", "part": 9, "title": "Mixture-of-Experts language models", "gap": false});
window.ALLML.push({"id": "9.7", "part": 9, "title": "KV cache & inference optimization", "gap": false});
window.ALLML.push({"id": "9.8", "part": 9, "title": "Quantized inference (GPTQ, AWQ)", "gap": false});
window.ALLML.push({"id": "9.9", "part": 9, "title": "Speculative decoding", "gap": false});
window.ALLML.push({"id": "9.10", "part": 9, "title": "Knowledge distillation for LMs (DistilBERT)", "gap": false});
window.ALLML.push({"id": "9.11", "part": 9, "title": "Full fine-tuning vs parameter-efficient (LoRA, adapters, prefix)", "gap": false});
window.ALLML.push({"id": "9.12", "part": 9, "title": "Instruction tuning", "gap": false});
window.ALLML.push({"id": "9.13", "part": 9, "title": "Reward modeling", "gap": false});
window.ALLML.push({"id": "9.14", "part": 9, "title": "RLHF", "gap": false});
window.ALLML.push({"id": "9.15", "part": 9, "title": "Preference optimization (DPO, IPO)", "gap": false});
window.ALLML.push({"id": "9.16", "part": 9, "title": "Constitutional AI", "gap": false});
window.ALLML.push({"id": "9.17", "part": 9, "title": "In-context learning", "gap": false});
window.ALLML.push({"id": "9.18", "part": 9, "title": "Prompting (zero/few-shot, chain-of-thought)", "gap": false});
window.ALLML.push({"id": "9.19", "part": 9, "title": "Advanced reasoning (self-consistency, tree/graph of thought, ReAct)", "gap": false});
window.ALLML.push({"id": "9.20", "part": 9, "title": "Tool use & function calling", "gap": true});
window.ALLML.push({"id": "9.21", "part": 9, "title": "LLM agents & orchestration", "gap": false});
window.ALLML.push({"id": "9.22", "part": 9, "title": "Retrieval-Augmented Generation", "gap": false});
window.ALLML.push({"id": "9.23", "part": 9, "title": "Hallucination & factuality", "gap": true});
window.ALLML.push({"id": "9.24", "part": 9, "title": "LLM evaluation & benchmarks", "gap": false});
window.ALLML.push({"id": "9.25", "part": 9, "title": "Guardrails & safety filtering", "gap": false});
window.ALLML.push({"id": "10.1", "part": 10, "title": "Autoencoders", "gap": false});
window.ALLML.push({"id": "10.2", "part": 10, "title": "Variational Autoencoders", "gap": false});
window.ALLML.push({"id": "10.3", "part": 10, "title": "VAE variants (beta-VAE, VQ-VAE)", "gap": false});
window.ALLML.push({"id": "10.4", "part": 10, "title": "Restricted Boltzmann Machines & Deep Belief Nets", "gap": false});
window.ALLML.push({"id": "10.5", "part": 10, "title": "Generative Adversarial Networks", "gap": false});
window.ALLML.push({"id": "10.6", "part": 10, "title": "GAN variants (DCGAN, WGAN, conditional)", "gap": false});
window.ALLML.push({"id": "10.7", "part": 10, "title": "StyleGAN & CycleGAN", "gap": false});
window.ALLML.push({"id": "10.8", "part": 10, "title": "GAN evaluation (FID, Inception Score)", "gap": false});
window.ALLML.push({"id": "10.9", "part": 10, "title": "Normalizing flows", "gap": false});
window.ALLML.push({"id": "10.10", "part": 10, "title": "Energy-based models", "gap": true});
window.ALLML.push({"id": "10.11", "part": 10, "title": "Score-based models & SDEs", "gap": false});
window.ALLML.push({"id": "10.12", "part": 10, "title": "Diffusion models (DDPM)", "gap": false});
window.ALLML.push({"id": "10.13", "part": 10, "title": "Classifier-free guidance", "gap": false});
window.ALLML.push({"id": "10.14", "part": 10, "title": "Latent diffusion & text-to-image", "gap": false});
window.ALLML.push({"id": "10.15", "part": 10, "title": "ControlNet & conditioning", "gap": false});
window.ALLML.push({"id": "10.16", "part": 10, "title": "Consistency & flow-matching models", "gap": false});
window.ALLML.push({"id": "10.17", "part": 10, "title": "Autoregressive generation (PixelCNN, WaveNet)", "gap": false});
window.ALLML.push({"id": "10.18", "part": 10, "title": "Neural style transfer", "gap": false});
window.ALLML.push({"id": "10.19", "part": 10, "title": "Video & 3D generation", "gap": false});
window.ALLML.push({"id": "11.1", "part": 11, "title": "RL framing (agent, environment, reward)", "gap": false});
window.ALLML.push({"id": "11.2", "part": 11, "title": "Markov Decision Processes", "gap": false});
window.ALLML.push({"id": "11.3", "part": 11, "title": "Bellman equations", "gap": false});
window.ALLML.push({"id": "11.4", "part": 11, "title": "Dynamic programming (policy & value iteration)", "gap": false});
window.ALLML.push({"id": "11.5", "part": 11, "title": "Monte Carlo methods", "gap": false});
window.ALLML.push({"id": "11.6", "part": 11, "title": "Temporal-Difference learning", "gap": false});
window.ALLML.push({"id": "11.7", "part": 11, "title": "Eligibility traces & TD(λ)", "gap": false});
window.ALLML.push({"id": "11.8", "part": 11, "title": "SARSA (on-policy)", "gap": false});
window.ALLML.push({"id": "11.9", "part": 11, "title": "Q-learning (off-policy)", "gap": false});
window.ALLML.push({"id": "11.10", "part": 11, "title": "Function approximation in RL", "gap": false});
window.ALLML.push({"id": "11.11", "part": 11, "title": "Deep Q-Networks", "gap": false});
window.ALLML.push({"id": "11.12", "part": 11, "title": "DQN variants (Double, Dueling, PER, Rainbow)", "gap": false});
window.ALLML.push({"id": "11.13", "part": 11, "title": "Distributional RL (C51, QR-DQN)", "gap": false});
window.ALLML.push({"id": "11.14", "part": 11, "title": "Policy gradients (REINFORCE)", "gap": false});
window.ALLML.push({"id": "11.15", "part": 11, "title": "Actor–Critic (A2C/A3C)", "gap": false});
window.ALLML.push({"id": "11.16", "part": 11, "title": "Generalized Advantage Estimation", "gap": false});
window.ALLML.push({"id": "11.17", "part": 11, "title": "TRPO & PPO", "gap": false});
window.ALLML.push({"id": "11.18", "part": 11, "title": "DDPG & TD3", "gap": false});
window.ALLML.push({"id": "11.19", "part": 11, "title": "Soft Actor-Critic", "gap": false});
window.ALLML.push({"id": "11.20", "part": 11, "title": "Model-based RL & world models", "gap": false});
window.ALLML.push({"id": "11.21", "part": 11, "title": "Exploration (ε-greedy, UCB, intrinsic motivation)", "gap": false});
window.ALLML.push({"id": "11.22", "part": 11, "title": "Multi-armed & contextual bandits", "gap": false});
window.ALLML.push({"id": "11.23", "part": 11, "title": "Hierarchical RL & options", "gap": false});
window.ALLML.push({"id": "11.24", "part": 11, "title": "POMDPs", "gap": true});
window.ALLML.push({"id": "11.25", "part": 11, "title": "Reward shaping", "gap": false});
window.ALLML.push({"id": "11.26", "part": 11, "title": "Goal-conditioned RL & hindsight replay", "gap": false});
window.ALLML.push({"id": "11.27", "part": 11, "title": "Multi-agent RL", "gap": false});
window.ALLML.push({"id": "11.28", "part": 11, "title": "Imitation & inverse RL", "gap": false});
window.ALLML.push({"id": "11.29", "part": 11, "title": "Offline RL", "gap": false});
window.ALLML.push({"id": "11.30", "part": 11, "title": "Meta-RL", "gap": false});
window.ALLML.push({"id": "11.31", "part": 11, "title": "Safe & constrained RL", "gap": false});
window.ALLML.push({"id": "11.32", "part": 11, "title": "Sim-to-real transfer", "gap": false});
window.ALLML.push({"id": "11.33", "part": 11, "title": "Decision transformers (RL as sequence modeling)", "gap": false});
window.ALLML.push({"id": "11.34", "part": 11, "title": "Self-play & population-based training", "gap": false});
window.ALLML.push({"id": "11.35", "part": 11, "title": "AlphaGo / AlphaZero / MuZero", "gap": false});
window.ALLML.push({"id": "12.1", "part": 12, "title": "Graph representation & tasks", "gap": false});
window.ALLML.push({"id": "12.2", "part": 12, "title": "Spectral graph theory", "gap": false});
window.ALLML.push({"id": "12.3", "part": 12, "title": "Node embeddings (DeepWalk, node2vec)", "gap": false});
window.ALLML.push({"id": "12.4", "part": 12, "title": "Message passing & Graph Convolutional Networks", "gap": false});
window.ALLML.push({"id": "12.5", "part": 12, "title": "GraphSAGE", "gap": false});
window.ALLML.push({"id": "12.6", "part": 12, "title": "Graph Attention Networks", "gap": false});
window.ALLML.push({"id": "12.7", "part": 12, "title": "Graph pooling", "gap": false});
window.ALLML.push({"id": "12.8", "part": 12, "title": "Graph autoencoders", "gap": false});
window.ALLML.push({"id": "12.9", "part": 12, "title": "Graph transformers", "gap": false});
window.ALLML.push({"id": "12.10", "part": 12, "title": "Link prediction", "gap": false});
window.ALLML.push({"id": "12.11", "part": 12, "title": "Community detection", "gap": false});
window.ALLML.push({"id": "12.12", "part": 12, "title": "Temporal & heterogeneous graphs", "gap": false});
window.ALLML.push({"id": "12.13", "part": 12, "title": "GNN expressiveness & the Weisfeiler–Leman test", "gap": false});
window.ALLML.push({"id": "12.14", "part": 12, "title": "Knowledge graphs & embeddings (TransE)", "gap": false});
window.ALLML.push({"id": "12.15", "part": 12, "title": "Geometric deep learning & equivariance", "gap": false});
window.ALLML.push({"id": "13.1", "part": 13, "title": "Audio representation (waveform, spectrogram, MFCC)", "gap": false});
window.ALLML.push({"id": "13.2", "part": 13, "title": "Automatic Speech Recognition", "gap": false});
window.ALLML.push({"id": "13.3", "part": 13, "title": "CTC & sequence transduction", "gap": false});
window.ALLML.push({"id": "13.4", "part": 13, "title": "Text-to-Speech synthesis", "gap": false});
window.ALLML.push({"id": "13.5", "part": 13, "title": "Self-supervised audio (wav2vec, HuBERT)", "gap": false});
window.ALLML.push({"id": "13.6", "part": 13, "title": "Speaker identification & diarization", "gap": true});
window.ALLML.push({"id": "13.7", "part": 13, "title": "Sound event detection", "gap": false});
window.ALLML.push({"id": "13.8", "part": 13, "title": "Music information retrieval & generation", "gap": false});
window.ALLML.push({"id": "14.1", "part": 14, "title": "Decomposition & stationarity", "gap": false});
window.ALLML.push({"id": "14.2", "part": 14, "title": "Autocorrelation & spectral analysis", "gap": false});
window.ALLML.push({"id": "14.3", "part": 14, "title": "AR, MA, ARIMA & SARIMA", "gap": false});
window.ALLML.push({"id": "14.4", "part": 14, "title": "Exponential smoothing (Holt-Winters)", "gap": false});
window.ALLML.push({"id": "14.5", "part": 14, "title": "State-space models", "gap": false});
window.ALLML.push({"id": "14.6", "part": 14, "title": "Prophet", "gap": true});
window.ALLML.push({"id": "14.7", "part": 14, "title": "Deep learning for time series (DeepAR, N-BEATS, TFT)", "gap": false});
window.ALLML.push({"id": "14.8", "part": 14, "title": "Time-series anomaly detection", "gap": false});
window.ALLML.push({"id": "14.9", "part": 14, "title": "Changepoint detection", "gap": false});
window.ALLML.push({"id": "14.10", "part": 14, "title": "Forecast evaluation & backtesting", "gap": true});
window.ALLML.push({"id": "15.1", "part": 15, "title": "Collaborative filtering", "gap": false});
window.ALLML.push({"id": "15.2", "part": 15, "title": "Matrix factorization", "gap": false});
window.ALLML.push({"id": "15.3", "part": 15, "title": "Content-based & hybrid recommenders", "gap": true});
window.ALLML.push({"id": "15.4", "part": 15, "title": "Learning to rank (pointwise, pairwise, listwise)", "gap": false});
window.ALLML.push({"id": "15.5", "part": 15, "title": "Ranking metrics (NDCG, MAP, MRR)", "gap": false});
window.ALLML.push({"id": "15.6", "part": 15, "title": "CTR prediction (Wide & Deep, DeepFM, DLRM)", "gap": false});
window.ALLML.push({"id": "15.7", "part": 15, "title": "Two-tower & neural retrieval recommenders", "gap": false});
window.ALLML.push({"id": "15.8", "part": 15, "title": "Sequential & session-based recommendation", "gap": true});
window.ALLML.push({"id": "15.9", "part": 15, "title": "The cold-start problem", "gap": true});
window.ALLML.push({"id": "15.10", "part": 15, "title": "Bandit-based recommendation", "gap": false});
window.ALLML.push({"id": "15.11", "part": 15, "title": "Recommender evaluation & bias", "gap": false});
window.ALLML.push({"id": "16.1", "part": 16, "title": "Inverted indexes & Boolean retrieval", "gap": false});
window.ALLML.push({"id": "16.2", "part": 16, "title": "BM25 & probabilistic retrieval", "gap": false});
window.ALLML.push({"id": "16.3", "part": 16, "title": "Vector-space models", "gap": false});
window.ALLML.push({"id": "16.4", "part": 16, "title": "Dense retrieval & embeddings", "gap": false});
window.ALLML.push({"id": "16.5", "part": 16, "title": "Approximate nearest neighbors (FAISS, HNSW, IVF)", "gap": false});
window.ALLML.push({"id": "16.6", "part": 16, "title": "Hybrid retrieval & re-ranking", "gap": false});
window.ALLML.push({"id": "16.7", "part": 16, "title": "Cross-encoders vs bi-encoders", "gap": false});
window.ALLML.push({"id": "16.8", "part": 16, "title": "Retrieval evaluation", "gap": false});
window.ALLML.push({"id": "17.1", "part": 17, "title": "Transfer learning", "gap": false});
window.ALLML.push({"id": "17.2", "part": 17, "title": "Domain adaptation & domain generalization", "gap": false});
window.ALLML.push({"id": "17.3", "part": 17, "title": "Semi-supervised learning", "gap": false});
window.ALLML.push({"id": "17.4", "part": 17, "title": "Self-supervised learning", "gap": false});
window.ALLML.push({"id": "17.5", "part": 17, "title": "Contrastive & metric learning (SimCLR, MoCo, triplet)", "gap": false});
window.ALLML.push({"id": "17.6", "part": 17, "title": "Multi-task learning", "gap": false});
window.ALLML.push({"id": "17.7", "part": 17, "title": "Meta-learning & few-shot (MAML, prototypical nets)", "gap": false});
window.ALLML.push({"id": "17.8", "part": 17, "title": "Zero-shot learning", "gap": false});
window.ALLML.push({"id": "17.9", "part": 17, "title": "Continual / lifelong learning", "gap": true});
window.ALLML.push({"id": "17.10", "part": 17, "title": "Active learning", "gap": true});
window.ALLML.push({"id": "17.11", "part": 17, "title": "Curriculum learning", "gap": true});
window.ALLML.push({"id": "17.12", "part": 17, "title": "Federated learning", "gap": true});
window.ALLML.push({"id": "17.13", "part": 17, "title": "Multimodal learning (CLIP, vision-language)", "gap": false});
window.ALLML.push({"id": "18.1", "part": 18, "title": "Exploratory data analysis", "gap": true});
window.ALLML.push({"id": "18.2", "part": 18, "title": "Data collection & sampling design", "gap": false});
window.ALLML.push({"id": "18.3", "part": 18, "title": "Data cleaning & missing-value handling", "gap": false});
window.ALLML.push({"id": "18.4", "part": 18, "title": "Data labeling & annotation", "gap": false});
window.ALLML.push({"id": "18.5", "part": 18, "title": "Weak supervision & programmatic labeling", "gap": false});
window.ALLML.push({"id": "18.6", "part": 18, "title": "Synthetic data generation", "gap": false});
window.ALLML.push({"id": "18.7", "part": 18, "title": "Data augmentation strategies", "gap": false});
window.ALLML.push({"id": "18.8", "part": 18, "title": "Data quality & validation", "gap": false});
window.ALLML.push({"id": "18.9", "part": 18, "title": "Data versioning & lineage", "gap": true});
window.ALLML.push({"id": "18.10", "part": 18, "title": "Data valuation & Shapley for data", "gap": true});
window.ALLML.push({"id": "19.1", "part": 19, "title": "Interpretability: feature importance & SHAP", "gap": false});
window.ALLML.push({"id": "19.2", "part": 19, "title": "Interpretability: LIME & saliency maps", "gap": false});
window.ALLML.push({"id": "19.3", "part": 19, "title": "Counterfactual explanations", "gap": false});
window.ALLML.push({"id": "19.4", "part": 19, "title": "Concept-based explanations (TCAV)", "gap": false});
window.ALLML.push({"id": "19.5", "part": 19, "title": "Influence functions", "gap": true});
window.ALLML.push({"id": "19.6", "part": 19, "title": "Fairness definitions & metrics (demographic parity, equalized odds)", "gap": false});
window.ALLML.push({"id": "19.7", "part": 19, "title": "Bias mitigation", "gap": false});
window.ALLML.push({"id": "19.8", "part": 19, "title": "Adversarial examples & attacks", "gap": false});
window.ALLML.push({"id": "19.9", "part": 19, "title": "Adversarial robustness & certification", "gap": false});
window.ALLML.push({"id": "19.10", "part": 19, "title": "Data poisoning & backdoors", "gap": true});
window.ALLML.push({"id": "19.11", "part": 19, "title": "Model extraction & stealing", "gap": true});
window.ALLML.push({"id": "19.12", "part": 19, "title": "Privacy attacks (membership inference)", "gap": false});
window.ALLML.push({"id": "19.13", "part": 19, "title": "Differential privacy", "gap": false});
window.ALLML.push({"id": "19.14", "part": 19, "title": "Machine unlearning", "gap": true});
window.ALLML.push({"id": "19.15", "part": 19, "title": "Watermarking & provenance", "gap": true});
window.ALLML.push({"id": "19.16", "part": 19, "title": "Uncertainty quantification & calibration", "gap": false});
window.ALLML.push({"id": "19.17", "part": 19, "title": "Conformal prediction", "gap": false});
window.ALLML.push({"id": "19.18", "part": 19, "title": "Out-of-distribution detection", "gap": false});
window.ALLML.push({"id": "19.19", "part": 19, "title": "Spurious correlations & shortcut learning", "gap": true});
window.ALLML.push({"id": "19.20", "part": 19, "title": "Causal inference (do-calculus, counterfactuals, propensity)", "gap": false});
window.ALLML.push({"id": "19.21", "part": 19, "title": "Uplift modeling", "gap": false});
window.ALLML.push({"id": "19.22", "part": 19, "title": "Red teaming & evaluation", "gap": true});
window.ALLML.push({"id": "20.1", "part": 20, "title": "ML system design", "gap": false});
window.ALLML.push({"id": "20.2", "part": 20, "title": "Data pipelines & feature stores", "gap": false});
window.ALLML.push({"id": "20.3", "part": 20, "title": "Experiment tracking & reproducibility", "gap": true});
window.ALLML.push({"id": "20.4", "part": 20, "title": "Data & model versioning; model registry", "gap": true});
window.ALLML.push({"id": "20.5", "part": 20, "title": "CI/CD for ML", "gap": false});
window.ALLML.push({"id": "20.6", "part": 20, "title": "Batch vs online (real-time) inference", "gap": false});
window.ALLML.push({"id": "20.7", "part": 20, "title": "Model serving & deployment", "gap": false});
window.ALLML.push({"id": "20.8", "part": 20, "title": "Monitoring & drift detection", "gap": false});
window.ALLML.push({"id": "20.9", "part": 20, "title": "A/B testing & online experimentation", "gap": false});
window.ALLML.push({"id": "20.10", "part": 20, "title": "Model compression: pruning", "gap": false});
window.ALLML.push({"id": "20.11", "part": 20, "title": "Model compression: quantization", "gap": false});
window.ALLML.push({"id": "20.12", "part": 20, "title": "Knowledge distillation", "gap": false});
window.ALLML.push({"id": "20.13", "part": 20, "title": "Distributed training (data/model/pipeline parallelism)", "gap": false});
window.ALLML.push({"id": "20.14", "part": 20, "title": "Compilation & runtimes (XLA, TVM, ONNX)", "gap": true});
window.ALLML.push({"id": "20.15", "part": 20, "title": "Vector databases & ANN infra", "gap": false});
window.ALLML.push({"id": "20.16", "part": 20, "title": "Streaming & real-time ML", "gap": false});
window.ALLML.push({"id": "20.17", "part": 20, "title": "LLMOps & prompt management", "gap": true});
window.ALLML.push({"id": "20.18", "part": 20, "title": "Evaluation harnesses", "gap": true});
window.ALLML.push({"id": "20.19", "part": 20, "title": "Cost & latency optimization", "gap": false});
window.ALLML.push({"id": "20.20", "part": 20, "title": "Edge & on-device ML", "gap": false});
window.ALLML.push({"id": "21.1", "part": 21, "title": "Propositional logic", "gap": false});
window.ALLML.push({"id": "21.2", "part": 21, "title": "First-order logic", "gap": false});
window.ALLML.push({"id": "21.3", "part": 21, "title": "Knowledge representation & reasoning", "gap": false});
window.ALLML.push({"id": "21.4", "part": 21, "title": "Description logics & ontologies", "gap": true});
window.ALLML.push({"id": "21.5", "part": 21, "title": "Semantic web & RDF", "gap": true});
window.ALLML.push({"id": "21.6", "part": 21, "title": "Rule-based & expert systems", "gap": false});
window.ALLML.push({"id": "21.7", "part": 21, "title": "Answer-set programming", "gap": false});
window.ALLML.push({"id": "21.8", "part": 21, "title": "SAT solvers", "gap": false});
window.ALLML.push({"id": "21.9", "part": 21, "title": "SMT solvers", "gap": false});
window.ALLML.push({"id": "21.10", "part": 21, "title": "Automated theorem proving", "gap": false});
window.ALLML.push({"id": "21.11", "part": 21, "title": "Case-based reasoning", "gap": false});
window.ALLML.push({"id": "21.12", "part": 21, "title": "Fuzzy logic", "gap": false});
window.ALLML.push({"id": "21.13", "part": 21, "title": "Constraint satisfaction problems", "gap": false});
window.ALLML.push({"id": "22.1", "part": 22, "title": "Uninformed search (BFS, DFS, UCS)", "gap": false});
window.ALLML.push({"id": "22.2", "part": 22, "title": "Iterative deepening & bidirectional search", "gap": false});
window.ALLML.push({"id": "22.3", "part": 22, "title": "Informed search & A*", "gap": false});
window.ALLML.push({"id": "22.4", "part": 22, "title": "Local search (hill climbing, simulated annealing, tabu)", "gap": false});
window.ALLML.push({"id": "22.5", "part": 22, "title": "Beam search", "gap": false});
window.ALLML.push({"id": "22.6", "part": 22, "title": "Adversarial search (minimax, alpha-beta)", "gap": false});
window.ALLML.push({"id": "22.7", "part": 22, "title": "Monte Carlo Tree Search", "gap": false});
window.ALLML.push({"id": "22.8", "part": 22, "title": "Automated planning (STRIPS, PDDL)", "gap": false});
window.ALLML.push({"id": "22.9", "part": 22, "title": "Hierarchical & partial-order planning", "gap": false});
window.ALLML.push({"id": "22.10", "part": 22, "title": "Planning under uncertainty (MDP/POMDP planning)", "gap": false});
window.ALLML.push({"id": "23.1", "part": 23, "title": "Normal-form games & Nash equilibrium", "gap": false});
window.ALLML.push({"id": "23.2", "part": 23, "title": "Extensive-form & sequential games", "gap": false});
window.ALLML.push({"id": "23.3", "part": 23, "title": "Cooperative game theory", "gap": false});
window.ALLML.push({"id": "23.4", "part": 23, "title": "Mechanism design & auctions", "gap": true});
window.ALLML.push({"id": "23.5", "part": 23, "title": "Social choice & voting", "gap": false});
window.ALLML.push({"id": "23.6", "part": 23, "title": "Markov / stochastic games", "gap": false});
window.ALLML.push({"id": "23.7", "part": 23, "title": "Multi-agent coordination & communication", "gap": false});
window.ALLML.push({"id": "23.8", "part": 23, "title": "Regret minimization & CFR", "gap": false});
window.ALLML.push({"id": "24.1", "part": 24, "title": "Genetic algorithms", "gap": true});
window.ALLML.push({"id": "24.2", "part": 24, "title": "Genetic programming", "gap": false});
window.ALLML.push({"id": "24.3", "part": 24, "title": "Evolution strategies (CMA-ES)", "gap": false});
window.ALLML.push({"id": "24.4", "part": 24, "title": "Differential evolution", "gap": false});
window.ALLML.push({"id": "24.5", "part": 24, "title": "Multi-objective optimization (NSGA-II)", "gap": false});
window.ALLML.push({"id": "24.6", "part": 24, "title": "Particle swarm optimization", "gap": false});
window.ALLML.push({"id": "24.7", "part": 24, "title": "Ant colony optimization", "gap": false});
window.ALLML.push({"id": "24.8", "part": 24, "title": "Neuroevolution (NEAT)", "gap": true});
window.ALLML.push({"id": "24.9", "part": 24, "title": "Memetic algorithms", "gap": true});
window.ALLML.push({"id": "25.1", "part": 25, "title": "Neurosymbolic integration", "gap": false});
window.ALLML.push({"id": "25.2", "part": 25, "title": "Inductive logic programming", "gap": false});
window.ALLML.push({"id": "25.3", "part": 25, "title": "Differentiable programming", "gap": false});
window.ALLML.push({"id": "25.4", "part": 25, "title": "Program synthesis", "gap": false});
window.ALLML.push({"id": "25.5", "part": 25, "title": "Neural theorem proving", "gap": false});
window.ALLML.push({"id": "27.1", "part": 27, "title": "Quantum machine learning", "gap": false});
window.ALLML.push({"id": "27.2", "part": 27, "title": "Neuromorphic computing", "gap": false});
window.ALLML.push({"id": "27.3", "part": 27, "title": "Foundation models & generalist agents", "gap": false});
window.ALLML.push({"id": "27.4", "part": 27, "title": "Embodied AI & robotics learning", "gap": false});
window.ALLML.push({"id": "27.5", "part": 27, "title": "Toward AGI: open problems", "gap": false});
