/* Edge labels for the concept mind-map (graph.html). Keyed by "<prereqId>>><lessonId>". */
window.GRAPH_LABELS = {
  // Foundations
  "fnd-vector>>>fnd-dot": "pair up coordinates",
  "fnd-vector>>>fnd-matrix": "stack rows of them",
  "fnd-dot>>>fnd-matvec": "row dotted with vector",
  "fnd-matrix>>>fnd-matvec": "rows act on vector",
  "fnd-vector>>>fnd-norm": "thing being measured",
  "fnd-dot>>>fnd-norm": "self dot, then root",
  "fnd-derivative>>>fnd-gradient": "slope per direction",
  "fnd-vector>>>fnd-gradient": "collect slopes into vector",
  "fnd-derivative>>>fnd-chain": "slopes multiply through",
  "fnd-matvec>>>fnd-eigen": "directions left unrotated",

  // Probability & Statistics
  "prob-sample-space>>>prob-axioms": "rules over outcomes",
  "prob-axioms>>>prob-conditional": "renormalize on evidence",
  "prob-conditional>>>prob-bayes": "flip the condition",
  "prob-conditional>>>prob-total-prob": "sum over cases",
  "prob-conditional>>>prob-independence": "when condition changes nothing",
  "prob-axioms>>>prob-counting": "count equally likely outcomes",
  "prob-axioms>>>prob-random-variable": "map outcomes to numbers",
  "prob-random-variable>>>prob-expectation": "probability-weighted average",
  "prob-expectation>>>prob-variance": "expected squared spread",
  "prob-expectation>>>prob-bernoulli-binomial": "mean of the count",
  "prob-counting>>>prob-bernoulli-binomial": "count success arrangements",
  "prob-random-variable>>>prob-bernoulli-binomial": "success-count variable",
  "prob-bernoulli-binomial>>>prob-geometric-poisson": "limits of repeated trials",
  "prob-random-variable>>>prob-pdf-cdf": "continuous-valued variable",
  "fnd-derivative>>>prob-pdf-cdf": "density is CDF slope",
  "prob-pdf-cdf>>>prob-uniform-exponential": "specific density shapes",
  "prob-pdf-cdf>>>prob-normal": "its bell-curve density",
  "prob-variance>>>prob-normal": "spread sets the width",
  "prob-random-variable>>>prob-joint-marginal": "several variables together",
  "prob-joint-marginal>>>prob-covariance-correlation": "how two vary jointly",
  "prob-variance>>>prob-covariance-correlation": "normalize to correlation",
  "prob-expectation>>>prob-conditional-expectation": "mean given evidence",
  "prob-joint-marginal>>>prob-conditional-expectation": "average over one variable",
  "prob-expectation>>>prob-inequalities": "bound from the mean",
  "prob-variance>>>prob-inequalities": "bound from the spread",
  "prob-expectation>>>prob-lln": "averages approach mean",
  "prob-inequalities>>>prob-lln": "bound the deviation",
  "prob-lln>>>prob-clt": "averages stabilize first",
  "prob-normal>>>prob-clt": "limit shape is Gaussian",
  "prob-expectation>>>prob-estimation": "estimate the mean",
  "prob-variance>>>prob-estimation": "quantify estimator spread",
  "prob-lln>>>prob-estimation": "more data, better estimate",

  // Machine Learning (CS229)
  "fnd-vector>>>ml-supervised": "features as vectors",
  "fnd-dot>>>ml-supervised": "score by weighted sum",
  "ml-supervised>>>ml-loss": "measure one prediction's error",
  "ml-loss>>>ml-cost": "average loss over data",
  "ml-cost>>>ml-gradient-descent": "surface to descend",
  "fnd-gradient>>>ml-gradient-descent": "step downhill along it",
  "ml-gradient-descent>>>ml-linear-regression": "fit weights by descent",
  "fnd-matvec>>>ml-linear-regression": "predictions for all rows",
  "fnd-dot>>>ml-linear-regression": "weighted sum of features",
  "ml-cost>>>ml-likelihood": "negative log-likelihood as cost",
  "prob-bayes>>>ml-likelihood": "probability of the data",
  "ml-linear-regression>>>ml-logistic-regression": "squash the linear score",
  "ml-likelihood>>>ml-logistic-regression": "fit by maximizing likelihood",
  "ml-logistic-regression>>>ml-softmax": "extend to many classes",
  "ml-linear-regression>>>ml-glm": "Gaussian special case",
  "ml-logistic-regression>>>ml-glm": "Bernoulli special case",
  "ml-logistic-regression>>>ml-svm": "linear boundary, new objective",
  "fnd-norm>>>ml-svm": "maximize the margin width",
  "ml-svm>>>ml-kernels": "replace inner products",
  "fnd-dot>>>ml-kernels": "kernel as implicit dot",
  "prob-bayes>>>ml-gda": "posterior from class densities",
  "prob-normal>>>ml-gda": "model classes as Gaussians",
  "ml-logistic-regression>>>ml-gda": "compare to discriminative",
  "prob-bayes>>>ml-naive-bayes": "posterior over classes",
  "ml-gda>>>ml-naive-bayes": "assume features independent",
  "ml-supervised>>>ml-trees": "labeled splits to learn",
  "ml-trees>>>ml-ensembles": "combine many trees",
  "fnd-norm>>>ml-knn": "distance to neighbors",
  "ml-supervised>>>ml-knn": "labels of neighbors",
  "ml-knn>>>ml-bias-variance": "k controls the tradeoff",
  "ml-linear-regression>>>ml-bias-variance": "underfit, high bias",
  "ml-bias-variance>>>ml-learning-theory": "bound generalization gap",
  "fnd-norm>>>ml-kmeans": "distance to centroids",
  "fnd-vector>>>ml-kmeans": "points in feature space",
  "ml-kmeans>>>ml-em": "soft version of assignment",
  "prob-bayes>>>ml-em": "responsibilities via posterior",
  "prob-normal>>>ml-em": "clusters as Gaussians",
  "ml-kmeans>>>ml-hierarchical": "merge instead of partition",
  "fnd-norm>>>ml-hierarchical": "distance between clusters",
  "fnd-eigen>>>ml-pca": "axes of max variance",
  "fnd-norm>>>ml-pca": "project and measure length",
  "ml-pca>>>ml-ica": "go beyond uncorrelated",
  "ml-logistic-regression>>>ml-classification-metrics": "score its predictions",
  "ml-classification-metrics>>>ml-roc-auc": "sweep the threshold",
  "ml-linear-regression>>>ml-regression-metrics": "score continuous predictions",
  "ml-loss>>>ml-regression-metrics": "errors aggregated",
  "ml-bias-variance>>>ml-regularization": "trade bias to cut variance",
  "fnd-norm>>>ml-regularization": "penalize weight size",
  "ml-linear-regression>>>ml-regularization": "shrink the coefficients",

  // Deep Learning (CS230)
  "fnd-dot>>>dl-neuron": "weighted sum plus bias",
  "dl-neuron>>>dl-activations": "bend the linear output",
  "dl-neuron>>>dl-forward-prop": "chain neurons forward",
  "dl-activations>>>dl-forward-prop": "nonlinearity each layer",
  "dl-forward-prop>>>dl-cross-entropy": "outputs to compare",
  "ml-loss>>>dl-cross-entropy": "loss for probabilities",
  "ml-logistic-regression>>>dl-cross-entropy": "log-loss generalized",
  "fnd-chain>>>dl-backprop": "differentiate layer by layer",
  "ml-gradient-descent>>>dl-backprop": "gradients to update weights",
  "dl-forward-prop>>>dl-backprop": "cache values to reuse",
  "dl-cross-entropy>>>dl-backprop": "error to send backward",
  "dl-backprop>>>dl-optimizers": "smarter use of gradients",
  "dl-backprop>>>dl-minibatch": "gradient per small batch",
  "dl-forward-prop>>>dl-init": "keep activations well-scaled",
  "dl-forward-prop>>>dl-dropout": "randomly drop activations",
  "ml-regularization>>>dl-dropout": "regularize the network",
  "dl-forward-prop>>>dl-batchnorm": "normalize layer inputs",
  "fnd-norm>>>dl-batchnorm": "rescale by mean and variance",
  "dl-minibatch>>>dl-early-stopping": "watch loss across epochs",
  "ml-regularization>>>dl-early-stopping": "stop to avoid overfit",
  "fnd-dot>>>dl-conv": "filter dotted over patch",
  "dl-conv>>>dl-pooling": "downsample feature maps",
  "dl-conv>>>dl-conv-hyperparams": "stride and padding effects",
  "dl-conv>>>dl-cnn-params": "weights per filter",
  "dl-conv-hyperparams>>>dl-cnn-params": "size sets the count",
  "dl-conv>>>dl-object-detection": "features for detection",
  "dl-pooling>>>dl-object-detection": "shrink the feature grid",
  "dl-forward-prop>>>dl-face-recognition": "embed each face",
  "fnd-norm>>>dl-face-recognition": "distance between embeddings",
  "dl-conv>>>dl-style-transfer": "feature maps carry style",
  "dl-forward-prop>>>dl-gan": "generator and discriminator nets",
  "dl-backprop>>>dl-gan": "train both adversarially",
  "dl-forward-prop>>>dl-rnn": "unroll over time steps",
  "dl-rnn>>>dl-vanishing-gradient": "gradients shrink across steps",
  "dl-backprop>>>dl-vanishing-gradient": "products through many layers",
  "dl-rnn>>>dl-lstm-gru": "add gates to recurrence",
  "dl-vanishing-gradient>>>dl-lstm-gru": "gates preserve gradient",
  "fnd-vector>>>dl-word-embeddings": "words as dense vectors",
  "fnd-matvec>>>dl-word-embeddings": "lookup as matrix row",
  "dl-word-embeddings>>>dl-word2vec": "learn the vectors",
  "ml-logistic-regression>>>dl-word2vec": "predict context words",
  "fnd-dot>>>dl-cosine-similarity": "numerator is the dot",
  "fnd-norm>>>dl-cosine-similarity": "normalize to compare angle",
  "dl-rnn>>>dl-attention": "improve over recurrence",
  "dl-word2vec>>>dl-attention": "weight word vectors",
  "dl-conv>>>dl-data-augmentation": "expand image training set",

  // Artificial Intelligence (CS221)
  "fnd-dot>>>ai-linear-predictors": "score features by weights",
  "ai-linear-predictors>>>ai-loss-minimization": "predictions to penalize",
  "ml-loss>>>ai-loss-minimization": "objective to minimize",
  "ai-loss-minimization>>>ai-sgd": "objective to descend",
  "ml-gradient-descent>>>ai-sgd": "step on one example",
  "ai-search-problem>>>ai-tree-search": "explore the state tree",
  "ai-tree-search>>>ai-graph-search": "reuse repeated states",
  "ai-graph-search>>>ai-astar": "add a heuristic guide",
  "ai-search-problem>>>ai-mdp": "search with random outcomes",
  "prob-conditional>>>ai-mdp": "transition probabilities",
  "ai-mdp>>>ai-policy-value": "evaluate a policy",
  "prob-expectation>>>ai-policy-value": "expected future reward",
  "ai-policy-value>>>ai-qvalue": "value of state-action",
  "ai-qvalue>>>ai-value-iteration": "iterate the Q updates",
  "ai-qvalue>>>ai-q-learning": "learn Q from experience",
  "ai-value-iteration>>>ai-q-learning": "sampled version of it",
  "ai-minimax>>>ai-alpha-beta": "prune useless branches",
  "ai-minimax>>>ai-expectimax": "chance nodes replace min",
  "prob-expectation>>>ai-expectimax": "average over chance",
  "ai-csp>>>ai-csp-search": "assign satisfying constraints",
  "prob-bayes>>>ai-bayes-net": "factor the joint distribution",
  "prob-conditional>>>ai-bayes-net": "edges as conditionals",
  "ai-bayes-net>>>ai-bayes-inference": "query the network",
  "ai-bayes-net>>>ai-hmm": "chain of hidden states",
  "prob-conditional>>>ai-hmm": "transition and emission",
  "ai-propositional-logic>>>ai-inference-rules": "derive new facts",

  // Linear Algebra (deep dive)
  "fnd-dot>>>la-matmul": "entry is a dot product",
  "fnd-matrix>>>la-matmul": "operands being multiplied",
  "fnd-matvec>>>la-matmul": "columns mapped one by one",
  "fnd-matrix>>>la-transpose": "flip its rows and columns",
  "la-matmul>>>la-transpose": "reverses product order",
  "la-matmul>>>la-identity-diagonal": "identity leaves it unchanged",
  "fnd-matvec>>>la-identity-diagonal": "diagonal scales each axis",
  "la-matmul>>>la-inverse": "product gives identity",
  "la-identity-diagonal>>>la-inverse": "target is identity",
  "la-inverse>>>la-determinant": "zero means no inverse",
  "fnd-matvec>>>la-determinant": "volume scaling factor",
  "fnd-matrix>>>la-trace": "sum of diagonal entries",
  "la-matmul>>>la-trace": "cyclic under products",
  "fnd-eigen>>>la-trace": "sums the eigenvalues",
  "fnd-matvec>>>la-rank-independence": "image spans which directions",
  "la-matmul>>>la-rank-independence": "rank limits the product",
  "la-transpose>>>la-psd": "symmetric form required",
  "fnd-dot>>>la-psd": "quadratic stays nonnegative",
  "fnd-eigen>>>la-psd": "eigenvalues nonnegative",
  "fnd-eigen>>>la-spectral": "eigenvectors form a basis",
  "la-transpose>>>la-spectral": "symmetry guarantees it",
  "la-identity-diagonal>>>la-spectral": "diagonalize the matrix",
  "la-psd>>>la-spectral": "real nonnegative spectrum",
  "la-spectral>>>la-svd": "eigendecompose ATA",
  "la-rank-independence>>>la-svd": "rank counts nonzero values",
  "la-matmul>>>la-svd": "factor into three matrices",
  "fnd-gradient>>>la-jacobian": "stack partials per output",
  "fnd-matvec>>>la-jacobian": "local map d to J d",
  "la-determinant>>>la-cofactor": "expand into smaller dets",
  "la-determinant>>>la-jacobian": "det is area scaling",
  "la-jacobian>>>la-hessian": "Hessian is Jacobian of the gradient",
  "fnd-gradient>>>la-hessian": "derivative of the gradient",
  "la-psd>>>la-hessian": "positive means convex",
  "la-determinant>>>la-hessian": "sign test for curvature",

  // Probability (advanced)
  "prob-pdf-cdf>>>probx-derived": "transform the density",
  "prob-expectation>>>probx-derived": "moments of the result",
  "prob-pdf-cdf>>>probx-convolution": "convolve the densities",
  "prob-normal>>>probx-convolution": "sum of Gaussians is Gaussian",
  "prob-variance>>>probx-total-variance": "decompose the variance",
  "prob-conditional-expectation>>>probx-total-variance": "average of conditionals",
  "prob-expectation>>>probx-mgf": "expectation of exponential",
  "prob-variance>>>probx-mgf": "derivatives give moments",

  // Machine Learning — more
  "ml-gradient-descent>>>mlx-newton": "use curvature for steps",
  "fnd-gradient>>>mlx-newton": "set gradient to zero",
  "ml-linear-regression>>>mlx-lwr": "weight nearby points",
  "ml-bias-variance>>>mlx-cross-validation": "estimate generalization error",
  "ml-regression-metrics>>>mlx-cross-validation": "score on each fold",
  "ml-bias-variance>>>mlx-model-selection": "penalize complexity",
  "ml-regression-metrics>>>mlx-model-selection": "fit measures the score",
  "ml-kmeans>>>mlx-clustering-metrics": "score the clusters",
  "ml-bias-variance>>>mlx-error-analysis": "diagnose error sources",

  // Artificial Intelligence — more
  "ai-astar>>>aix-relaxation": "relax to build heuristics",
  "ai-search-problem>>>aix-structured-perceptron": "predict a search path",
  "aix-relaxation>>>aix-structured-perceptron": "learn the edge costs",
  "ai-q-learning>>>aix-monte-carlo": "estimate from full returns",
  "ai-qvalue>>>aix-monte-carlo": "average sampled Q-values",
  "aix-monte-carlo>>>aix-sarsa-td": "bootstrap instead of waiting",
  "ai-q-learning>>>aix-sarsa-td": "on-policy variant",
  "ai-minimax>>>aix-game-theory": "simultaneous instead of turns",
  "prob-expectation>>>aix-game-theory": "expected payoff over mixes",
  "ai-bayes-net>>>aix-variable-elimination": "eliminate hidden variables",
  "ai-bayes-inference>>>aix-variable-elimination": "exact query method",
  "ai-bayes-inference>>>aix-gibbs-particle": "approximate by sampling",
  "aix-variable-elimination>>>aix-gibbs-particle": "fallback when exact too costly",
  "ai-bayes-net>>>aix-markov-blanket": "node's neighbor shield",
  "aix-gibbs-particle>>>aix-markov-blanket": "resample given the blanket",
  "ai-hmm>>>aix-forward-backward": "combine both directions",
  "aix-variable-elimination>>>aix-forward-backward": "elimination along the chain",
  "aix-gibbs-particle>>>aix-lda-topic": "sample topic assignments",
  "ai-bayes-net>>>aix-lda-topic": "generative topic model",
  "ai-propositional-logic>>>aix-fol": "add quantifiers and objects",
  "ai-inference-rules>>>aix-fol": "resolution with unification",

  // Classical ML (beyond the cheat sheet)
  "ml-kmeans>>>cls-gmm": "soft probabilistic clusters",
  "ml-gda>>>cls-gmm": "mixture of Gaussians",
  "prob-normal>>>cls-gmm": "each component Gaussian",
  "ml-kmeans>>>cls-dbscan": "cluster without fixed k",
  "ml-kmeans>>>cls-spectral-clustering": "cluster in eigenspace",
  "ml-pca>>>cls-spectral-clustering": "eigenvectors of the graph",
  "ml-gda>>>cls-lda-qda": "shared versus separate covariance",
  "prob-normal>>>cls-lda-qda": "Gaussian class densities",
  "ml-linear-regression>>>cls-gaussian-process": "distribution over functions",
  "prob-normal>>>cls-gaussian-process": "jointly Gaussian outputs",
  "ml-pca>>>cls-gaussian-process": "kernel covariance structure",
  "ml-linear-regression>>>cls-bayesian-regression": "put priors on weights",
  "ml-likelihood>>>cls-bayesian-regression": "combine with the prior",
  "prob-normal>>>cls-bayesian-regression": "Gaussian prior and posterior",
  "ml-ensembles>>>cls-gradient-boosting": "boost trees sequentially",
  "ml-gradient-descent>>>cls-gradient-boosting": "fit residual gradients",
  "ml-ensembles>>>cls-stacking": "combine many models",
  "ml-linear-regression>>>cls-stacking": "meta-model blends outputs",
  "ml-ensembles>>>cls-anomaly": "isolate rare points",
  "ml-linear-regression>>>cls-recommender": "factorize the rating matrix",
  "ml-pca>>>cls-recommender": "low-rank latent factors",
  "ml-pca>>>cls-tsne": "linear baseline to beat",
  "ml-knn>>>cls-tsne": "preserve local neighbors",
  "ml-pca>>>cls-factor-analysis": "latent factors with noise",
  "ml-linear-regression>>>cls-factor-analysis": "linear factor model",
  "ml-svm>>>cls-svr": "margin around the fit",
  "ml-linear-regression>>>cls-svr": "regress within a tube",
  "ml-knn>>>cls-bandits": "explore versus exploit arms",

  // Modern Deep Learning & AI
  "dl-attention>>>mod-transformer": "attention replaces recurrence",
  "dl-word-embeddings>>>mod-transformer": "token vectors as input",
  "mod-transformer>>>mod-multihead": "parallel attention heads",
  "mod-transformer>>>mod-llm": "stacked transformer blocks",
  "prob-normal>>>mod-llm": "sample the next token",
  "dl-backprop>>>mod-autoencoder": "train to reconstruct input",
  "dl-neuron>>>mod-autoencoder": "encoder and decoder layers",
  "mod-autoencoder>>>mod-vae": "make the latent probabilistic",
  "prob-normal>>>mod-vae": "Gaussian latent space",
  "dl-backprop>>>mod-diffusion": "train the denoiser",
  "prob-normal>>>mod-diffusion": "add and remove Gaussian noise",
  "prob-normal>>>mod-normalizing-flows": "transform a simple density",
  "dl-backprop>>>mod-normalizing-flows": "train invertible maps",
  "dl-backprop>>>mod-gnn": "train over the graph",
  "dl-forward-prop>>>mod-gnn": "pass messages between nodes",
  "ai-q-learning>>>mod-dqn": "approximate Q with a net",
  "dl-backprop>>>mod-dqn": "train the Q-network",
  "ai-q-learning>>>mod-policy-gradient": "optimize policy directly",
  "dl-cross-entropy>>>mod-policy-gradient": "log-prob of actions",
  "ml-gradient-descent>>>mod-policy-gradient": "ascend expected reward",
  "mod-policy-gradient>>>mod-actor-critic": "add a value baseline",
  "ai-value-iteration>>>mod-actor-critic": "critic estimates value",
  "dl-cross-entropy>>>mod-contrastive": "pull positives, push negatives",
  "dl-forward-prop>>>mod-contrastive": "embed the inputs",
  "dl-forward-prop>>>mod-vit": "patches through the encoder",
  "dl-cross-entropy>>>mod-vit": "classify the image",
  "ml-gradient-descent>>>mod-timeseries": "fit the model parameters"
};
