module.exports = {
  "math-04-23": {
    id: "math-04-23",
    title: "Sequences of functions",
    tagline: "A sequence of functions is a whole list of curves, and convergence asks what curve the list is becoming.",
    connections: { buildsOn: ["sequences", "functions", "limits"], leadsTo: ["pointwise convergence", "uniform convergence", "series of functions"], usedWith: ["supremum norms", "continuity", "limits of functions"] },
    motivation: `<p>You already know a numerical sequence like $1,1/2,1/3,\\ldots$ can settle toward $0$. Now replace each number by an entire function. Instead of one dot moving, a whole curve moves.</p><p>A <b>sequence of functions</b> lets us study approximations that improve step by step: polynomials approaching a target, kernels getting sharper, or models becoming more expressive. The warm question is the same as before: as $n$ grows, what remains?</p>`,
    definition: `<p>A sequence of functions is a list $f_1,f_2,f_3,\\ldots$ where each $f_n$ maps the same domain $D$ into numbers. A candidate limit $f$ is found by checking, for each fixed input $x\\in D$, whether $f_n(x)$ approaches a number. In symbols, $f(x)=\\lim_{n\\to\\infty}f_n(x)$ when the limit exists.</p><p><b>Assumptions that matter:</b> all functions should be compared on a stated domain; the input $x$ is held fixed when taking the limit; and endpoints can behave differently from interior points.</p>`,
    worked: { problem: "For $f_n(x)=x^n$ on $[0,1]$, find the pointwise limit.", skills: ["fixed-input limits", "endpoint checking", "piecewise functions"], strategy: "Hold $x$ fixed. Interior points with $0\\le x<1$ behave differently from $x=1$.", steps: [
      { do: "Check $x=0$", result: "$f_n(0)=0^n=0$", why: "every term is zero" },
      { do: "Check a fixed $0<x<1$", result: "$x^n\\to0$", why: "repeated multiplication by a number below $1$ shrinks to zero" },
      { do: "Check $x=1$", result: "$f_n(1)=1^n=1$", why: "the endpoint never changes" },
      { do: "Assemble the limit", result: "$f(x)=0$ for $0\\le x<1$ and $f(1)=1$", why: "the cases give different values" }
    ], verify: "At $x=0.5$, $0.5^{10}\\approx0.00098$, close to $0$; at $x=1$, every value is exactly $1$.", answer: "The pointwise limit is $f(x)=0$ on $[0,1)$ and $f(1)=1$.", connects: "This example prepares the distinction between pointwise and uniform convergence." },
    practice: [
      { problem: "Find the pointwise limit of $f_n(x)=x/n$ on $[-2,2]$.", steps: [{ do: "Fix $x$", result: "$f_n(x)=x/n$", why: "pointwise convergence treats $x$ as constant" }, { do: "Take the numerical limit", result: "$x/n\\to0$", why: "a fixed number divided by $n$ vanishes" }, { do: "Check a sample", result: "$f_{100}(2)=0.02$", why: "values shrink on the interval" }, { do: "State the limit", result: "$f(x)=0$", why: "every fixed input has the same limit" }], answer: "$f_n\\to0$ pointwise." },
      { problem: "Find the pointwise limit of $f_n(x)=\\dfrac{nx}{1+nx}$ on $[0,1]$.", steps: [{ do: "Check $x=0$", result: "$f_n(0)=0$", why: "the numerator is zero" }, { do: "Fix $x>0$", result: "$\\dfrac{nx}{1+nx}=\\dfrac{1}{1+1/(nx)}$", why: "divide by $nx$" }, { do: "Take $n\\to\\infty$", result: "$\\dfrac{1}{1+0}=1$", why: "$1/(nx)\\to0$" }, { do: "Assemble", result: "$f(0)=0$, $f(x)=1$ for $x>0$", why: "the endpoint differs" }], answer: "$f(0)=0$ and $f(x)=1$ for $0<x\\le1$." },
      { problem: "For $f_n(x)=\\sin(x/n)$ on $[-10,10]$, find the pointwise limit.", steps: [{ do: "Fix $x$", result: "$x/n\\to0$", why: "the angle shrinks" }, { do: "Use continuity", result: "$\\sin(x/n)\\to\\sin0$", why: "sine preserves limits" }, { do: "Evaluate", result: "$\\sin0=0$", why: "standard trig value" }, { do: "State the limit", result: "$f(x)=0$", why: "the same result holds for each fixed input" }], answer: "$0$ pointwise." },
      { problem: "For $f_n(x)=1+x^2/n$ on $[-3,3]$, find the pointwise limit.", steps: [{ do: "Fix $x$", result: "$x^2$ is constant", why: "the input is not moving" }, { do: "Take the changing term", result: "$x^2/n\\to0$", why: "fixed numerator over growing denominator" }, { do: "Combine with $1$", result: "$1+0=1$", why: "limits add" }, { do: "Check $x=3$", result: "$f_{100}(3)=1.09$", why: "even the endpoint moves toward $1$" }], answer: "$f_n\\to1$ pointwise." },
      { problem: "For fixed $x\\ge0$, find $\\lim_{n\\to\\infty}\\left(1-\\dfrac{x}{n}\\right)^n$.", steps: [{ do: "Recognize the pattern", result: "$(1+a/n)^n\\to e^a$", why: "standard exponential limit" }, { do: "Set $a=-x$", result: "$\\left(1-\\dfrac{x}{n}\\right)^n=(1+a/n)^n$", why: "match the form" }, { do: "Take the limit", result: "$e^{-x}$", why: "the fixed input becomes the exponent" }, { do: "Check $x=2$", result: "$(1-2/100)^{100}\\approx0.133$", why: "close to $e^{-2}\\approx0.135$" }], answer: "$e^{-x}$ pointwise for fixed $x$." }
    ],
    applications: [
      { title: "Polynomial approximation", background: "Approximation theory replaces complicated functions by improving polynomial lists.", numbers: "$p_3(1)=1+1+1/2+1/6=2.667$ and $p_6(1)\\approx2.7181$, approaching $e\\approx2.7183$." },
      { title: "Kernel bandwidths", background: "Statistics studies sequences of kernels as smoothing becomes sharper.", numbers: "For $f_n(x)=e^{-nx^2}$, $f_{10}(0.2)=e^{-0.4}\\approx0.670$ but $f_{100}(0.2)=e^{-4}\\approx0.018$." },
      { title: "Training snapshots", background: "A model after each epoch is a function from inputs to predictions.", numbers: "For one input, predictions $0.20,0.35,0.44,0.49$ suggest a fixed-input limit near $0.5$." },
      { title: "Iterative solvers", background: "Numerical methods often output one approximate function per iteration.", numbers: "$f_n(x)=\\cos(x)/n$ has $f_{20}(1)\\approx0.027$ and tends to $0$." },
      { title: "Regularization paths", background: "Changing a penalty creates a sequence of fitted functions.", numbers: "$f_n(x)=x/(1+1/n)$ gives $f_{10}(2)=1.818$ and $f_{100}(2)=1.980$, approaching $2$." },
      { title: "Wide-network limits", background: "Theory treats each width as a function and asks whether predictions settle.", numbers: "If $|f_n(x)-f(x)|\\le0.1/n$, then at width index $n=50$ the error is at most $0.002$." }
    ],
    applicationsClose: "Sequences of functions let one familiar limit idea act on whole curves, but the domain and fixed-input rule matter deeply.",
    takeaways: ["A sequence of functions is a list $f_n$ on a common domain.", "Pointwise analysis fixes $x$ first, then sends $n\\to\\infty$.", "Endpoints often behave differently from interior points.", "These sequences lead naturally to pointwise and uniform convergence."]
  },

  "math-04-24": {
    id: "math-04-24",
    title: "Series of functions",
    tagline: "A series of functions adds infinitely many curves and asks whether the sum curve is well-defined.",
    connections: { buildsOn: ["sequences of functions", "infinite series", "partial sums"], leadsTo: ["power series", "uniform convergence", "term-by-term differentiation"], usedWith: ["geometric series", "comparison tests", "supremum norms"] },
    motivation: `<p>You already know that $1+1/2+1/4+\\cdots=2$. A <b>series of functions</b> asks the same question with terms that depend on $x$: add one curve, then another, then another.</p><p>The partial sums are the honest way to watch the build. Each $S_N(x)$ is ordinary and finite; the series converges where these finite sums settle as $N$ grows.</p>`,
    definition: `<p>A series of functions has the form $\\sum_{n=0}^{\\infty} f_n(x)$. Its $N$th partial sum is $S_N(x)=\\sum_{n=0}^{N}f_n(x)$. The series converges at an input $x$ when $S_N(x)$ has a finite limit, and the sum function is $S(x)=\\lim_{N\\to\\infty}S_N(x)$.</p><p><b>Assumptions that matter:</b> convergence may hold for some inputs and fail for others; comparison tests often require bounding $|f_n(x)|$; and term-by-term operations need stronger convergence than pointwise convergence alone.</p>`,
    worked: { problem: "Find the sum of $\\sum_{n=0}^{\\infty} x^n$ for $|x|<1$.", skills: ["geometric series", "partial sums", "domain restrictions"], strategy: "Recognize a geometric series with ratio $x$, then state where the ratio has magnitude below $1$.", steps: [{ do: "Write the partial sum", result: "$S_N=1+x+x^2+\\cdots+x^N$", why: "finite sums are safe" }, { do: "Use the geometric formula", result: "$S_N=\\dfrac{1-x^{N+1}}{1-x}$", why: "valid for $x\\ne1$" }, { do: "Apply $|x|<1$", result: "$x^{N+1}\\to0$", why: "powers inside the unit interval vanish" }, { do: "Take the limit", result: "$S(x)=\\dfrac{1}{1-x}$", why: "the remaining expression is the infinite sum" }], verify: "At $x=0.5$, the first four terms sum to $1.875$ and the formula gives $2$, so the partial sums are moving toward the right value.", answer: "$\\sum_{n=0}^{\\infty}x^n=1/(1-x)$ for $|x|<1$.", connects: "Power series begin with this geometric example." },
    practice: [
      { problem: "Find $\\sum_{n=1}^{\\infty}\\dfrac{x^n}{2^n}$ for $|x|<2$.", steps: [{ do: "Rewrite the term", result: "$(x/2)^n$", why: "this is geometric" }, { do: "Identify the first term", result: "$x/2$", why: "the sum starts at $n=1$" }, { do: "Identify the ratio", result: "$r=x/2$", why: "each term multiplies by $x/2$" }, { do: "Use the sum", result: "$\\dfrac{x/2}{1-x/2}=\\dfrac{x}{2-x}$", why: "geometric formula" }], answer: "$x/(2-x)$ for $|x|<2$." },
      { problem: "For $\\sum_{n=1}^{\\infty}\\dfrac{x}{n^2}$, find the sum function.", steps: [{ do: "Factor out $x$", result: "$x\\sum_{n=1}^{\\infty}\\dfrac1{n^2}$", why: "$x$ does not depend on $n$" }, { do: "Use the known sum", result: "$\\sum 1/n^2=\\pi^2/6$", why: "Basel series" }, { do: "Multiply by $x$", result: "$S(x)=\\dfrac{\\pi^2}{6}x$", why: "constant factors pass through sums" }, { do: "Check $x=3$", result: "$S(3)=\\pi^2/2\\approx4.935$", why: "concrete value" }], answer: "$S(x)=\\pi^2x/6$." },
      { problem: "Test convergence of $\\sum_{n=1}^{\\infty} n x^n$ at $x=0.5$.", steps: [{ do: "Substitute $x=0.5$", result: "$\\sum n(0.5)^n$", why: "test a numerical series" }, { do: "Use the ratio test", result: "$\\dfrac{a_{n+1}}{a_n}=\\dfrac{n+1}{n}\\cdot0.5$", why: "compare consecutive terms" }, { do: "Take the limit", result: "$0.5$", why: "$(n+1)/n\\to1$" }, { do: "Apply the test", result: "converges", why: "the limiting ratio is less than $1$" }], answer: "Converges at $x=0.5$." },
      { problem: "Find where $\\sum_{n=0}^{\\infty} (3x)^n$ converges.", steps: [{ do: "Identify the ratio", result: "$r=3x$", why: "geometric series" }, { do: "Apply the condition", result: "$|3x|<1$", why: "ratio magnitude below $1$" }, { do: "Solve", result: "$|x|<1/3$", why: "divide by $3$" }, { do: "Check endpoints", result: "diverges at $x=\\pm1/3$", why: "terms do not approach zero" }], answer: "Converges for $|x|<1/3$." },
      { problem: "Approximate $\\sum_{n=0}^{\\infty}(-0.1)^n$ and bound the tail after $4$ terms.", steps: [{ do: "Use the sum formula", result: "$S=1/(1+0.1)=0.90909\\ldots$", why: "ratio is $-0.1$" }, { do: "Compute four terms", result: "$S_3=1-0.1+0.01-0.001=0.909$", why: "terms $n=0$ through $3$" }, { do: "Bound the tail", result: "$|R_3|\\le\\dfrac{0.1^4}{1-0.1}$", why: "geometric tail formula" }, { do: "Evaluate", result: "$0.000111\\ldots$", why: "$0.1^4=0.0001$" }], answer: "Sum $0.90909\\ldots$; four-term error at most about $0.000111$." }
    ],
    applications: [
      { title: "Fourier series", background: "Fourier showed that periodic signals can be represented as infinite sums of sine and cosine functions.", numbers: "$\\sin x+(1/3)\\sin3x+(1/5)\\sin5x$ uses amplitudes $1$, $0.333$, and $0.2$." },
      { title: "Taylor models", background: "Calculus approximates smooth functions by adding polynomial terms one by one.", numbers: "For $e^{0.5}$, $1+0.5+0.5^2/2+0.5^3/6=1.6458$, close to $1.6487$." },
      { title: "Kernel expansions", background: "Machine learning kernels can be understood through infinite feature expansions.", numbers: "For $e^{xy}$ with $xy=0.2$, $1+xy+(xy)^2/2=1.22$." },
      { title: "Boosting corrections", background: "Boosting adds correction functions to improve a current predictor.", numbers: "Corrections of sizes $0.4,0.2,0.1,0.05$ total $0.75$ after four rounds." },
      { title: "Signal compression", background: "Function series separate large low-frequency terms from small details.", numbers: "Coefficients $3$, $1$, and $0.25$ carry squared energy $9+1+0.0625=10.0625$." },
      { title: "Discounted returns", background: "Reinforcement learning uses infinite series of discounted rewards.", numbers: "With reward $2$ and discount $0.9$, total return is $2/(1-0.9)=20$." }
    ],
    applicationsClose: "Series of functions are infinite construction kits: convergence decides whether the construction has a stable final shape.",
    takeaways: ["A function series is studied through partial sums $S_N$.", "Geometric series provide the basic exact model.", "The convergence set can be smaller than the original domain.", "Applications rely on controlling tail error."]
  },

  "math-04-25": {
    id: "math-04-25",
    title: "Pointwise convergence",
    tagline: "Pointwise convergence watches one input at a time, like checking each seat in a stadium separately.",
    connections: { buildsOn: ["sequences of functions", "limits", "piecewise definitions"], leadsTo: ["uniform convergence", "continuity of limits", "interchange of limits and integrals"], usedWith: ["epsilon definitions", "counterexamples", "series of functions"] },
    motivation: `<p>You have already practiced limits of $f_n(x)$ by fixing $x$. <b>Pointwise convergence</b> names exactly that habit. For each input, ask whether the output sequence settles.</p><p>The kindness and the danger are the same: pointwise convergence is easy to check input by input, but it may hide uneven behavior across the domain. A limit curve can lose continuity even when every $f_n$ is continuous.</p>`,
    definition: `<p>A sequence $f_n$ converges <b>pointwise</b> to $f$ on $D$ if for every fixed $x\\in D$ and every $\\varepsilon>0$, there is an $N$ that may depend on $x$ and $\\varepsilon$ such that $n\\ge N$ implies $|f_n(x)-f(x)|<\\varepsilon$.</p><p><b>Assumptions that matter:</b> the phrase "for every fixed $x$" is essential; the required $N$ may change from point to point; pointwise convergence alone does not preserve continuity, boundedness, integrals, or derivatives.</p>`,
    worked: { problem: "Show that $f_n(x)=x^n$ converges pointwise on $[0,1]$ and identify the limit.", skills: ["pointwise definition", "endpoint cases", "piecewise limits"], strategy: "Use separate fixed-input cases: $0\\le x<1$ and $x=1$.", steps: [{ do: "Fix $0\\le x<1$", result: "$x^n\\to0$", why: "powers of a fixed number below $1$ vanish" }, { do: "Fix $x=1$", result: "$1^n=1$", why: "the endpoint never changes" }, { do: "Define the candidate", result: "$f(x)=0$ for $x<1$ and $f(1)=1$", why: "each fixed input has a numerical limit" }, { do: "Name the convergence", result: "$f_n\\to f$ pointwise", why: "the limit exists at every input" }], verify: "At $x=0.9$, many terms are needed: $0.9^{100}\\approx0.000027$; at $x=1$ no shrinking happens.", answer: "Pointwise limit $f(x)=0$ for $0\\le x<1$ and $f(1)=1$.", connects: "This example shows why pointwise convergence can preserve each input but not graph shape." },
    practice: [
      { problem: "Show $f_n(x)=\\dfrac{x}{n+x}$ converges pointwise to $0$ on $[0,10]$.", steps: [{ do: "Fix $x$", result: "$x/(n+x)$", why: "treat $x$ as constant" }, { do: "Divide by $n$", result: "$\\dfrac{x/n}{1+x/n}$", why: "make the limit visible" }, { do: "Take the limit", result: "$0/(1+0)=0$", why: "$x/n\\to0$" }, { do: "State convergence", result: "$f_n(x)\\to0$", why: "works for every fixed $x$" }], answer: "Pointwise limit $0$." },
      { problem: "Find the pointwise limit of $f_n(x)=\\mathbf{1}_{[0,1/n]}(x)$ on $[0,1]$.", steps: [{ do: "Check $x=0$", result: "$f_n(0)=1$", why: "zero belongs to every interval" }, { do: "Fix $x>0$", result: "choose $N>1/x$", why: "then $1/n<x$ for $n\\ge N$" }, { do: "Evaluate for $n\\ge N$", result: "$f_n(x)=0$", why: "$x$ is no longer in the interval" }, { do: "Assemble", result: "$f(0)=1$, $f(x)=0$ for $x>0$", why: "one point remains different" }], answer: "$f(0)=1$ and $f(x)=0$ for $0<x\\le1$." },
      { problem: "Does $f_n(x)=\\cos x+1/n$ converge pointwise on $\\mathbb{R}$?", steps: [{ do: "Fix $x$", result: "$\\cos x$ is constant", why: "only $1/n$ changes" }, { do: "Take the changing limit", result: "$1/n\\to0$", why: "standard sequence" }, { do: "Combine", result: "$\\cos x+1/n\\to\\cos x$", why: "limits add" }, { do: "State the limit", result: "$f(x)=\\cos x$", why: "valid for every real input" }], answer: "Yes, pointwise to $\\cos x$." },
      { problem: "Find the pointwise limit of $f_n(x)=\\dfrac{1}{1+n x^2}$ on $\\mathbb{R}$.", steps: [{ do: "Check $x=0$", result: "$f_n(0)=1$", why: "denominator is always $1$" }, { do: "Fix $x\\ne0$", result: "$nx^2\\to\\infty$", why: "$x^2$ is positive" }, { do: "Take the reciprocal limit", result: "$1/(1+nx^2)\\to0$", why: "denominator grows" }, { do: "Assemble", result: "$f(0)=1$, $f(x)=0$ for $x\\ne0$", why: "the spike narrows" }], answer: "$f(0)=1$ and $f(x)=0$ otherwise." },
      { problem: "For $f_n(x)=\\min(nx,1)$ on $[0,1]$, find the pointwise limit.", steps: [{ do: "Check $x=0$", result: "$f_n(0)=0$", why: "the minimum of $0$ and $1$ is $0$" }, { do: "Fix $x>0$", result: "choose $N\\ge1/x$", why: "then $nx\\ge1$" }, { do: "Evaluate after that", result: "$f_n(x)=1$", why: "the minimum becomes $1$" }, { do: "Assemble", result: "$f(0)=0$, $f(x)=1$ for $x>0$", why: "transition sharpens" }], answer: "$f(0)=0$ and $f(x)=1$ for $0<x\\le1$." }
    ],
    applications: [
      { title: "Threshold classifiers", background: "Smooth threshold approximations can converge pointwise to a hard rule.", numbers: "$\\sigma(10(0.6-0.5))=0.731$ and $\\sigma(50(0.6-0.5))=0.993$, approaching $1$." },
      { title: "Narrowing kernels", background: "Density kernels may become spikes, disappearing away from the center.", numbers: "$e^{-10(0.2)^2}=0.670$ but $e^{-100(0.2)^2}=0.018$." },
      { title: "Model snapshots", background: "Training predictions at one example form a numerical sequence.", numbers: "Predicted probabilities $0.40,0.46,0.49,0.505$ suggest a limit near $0.5$." },
      { title: "Grid refinement", background: "Approximations can converge at each fixed coordinate as a grid is refined.", numbers: "If point error is $2^{-n}$, after $10$ refinements it is $1/1024\\approx0.00098$." },
      { title: "Regularization annealing", background: "Reduced penalties can approach an unpenalized fit at each input.", numbers: "$f_n(3)=3/(1+0.2/n)$ gives $2.884$ at $n=5$ and $2.988$ at $n=50$." },
      { title: "Sensor simulations", background: "Simulations are often checked at fixed sensor locations.", numbers: "Temperature estimates $21.0,21.4,21.49,21.501$ suggest a pointwise limit near $21.5$." }
    ],
    applicationsClose: "Pointwise convergence is honest but local: it tells the truth at every fixed input while allowing global shape to change sharply.",
    takeaways: ["Pointwise convergence fixes $x$ first and lets $n$ grow.", "The required $N$ may depend on the input.", "Continuous functions can converge pointwise to a discontinuous limit.", "Uniform convergence strengthens this by choosing one $N$ for all inputs."]
  },

  "math-04-26": {
    id: "math-04-26",
    title: "Uniform convergence",
    tagline: "Uniform convergence means the whole graph gets close at once, not just one input at a time.",
    connections: { buildsOn: ["pointwise convergence", "supremum", "absolute value distance"], leadsTo: ["interchanging limits and integrals", "power series convergence", "complete metric spaces"], usedWith: ["Cauchy criteria", "Weierstrass M-test", "continuity of limits"] },
    motivation: `<p>Pointwise convergence can feel like checking one tile at a time. <b>Uniform convergence</b> asks for something stronger: after some stage, every tile is close at once.</p><p>The mental picture is a shrinking tube around the limit function. Uniform convergence says the entire graph of $f_n$ eventually fits inside any tube of radius $\\varepsilon$ around $f$.</p>`,
    definition: `<p>A sequence $f_n$ converges <b>uniformly</b> to $f$ on $D$ if for every $\\varepsilon>0$ there is an $N$ such that for all $n\\ge N$ and all $x\\in D$, $|f_n(x)-f(x)|<\\varepsilon$. Equivalently, $\\sup_{x\\in D}|f_n(x)-f(x)|\\to0$.</p><p><b>Assumptions that matter:</b> the same $N$ must work for every input; the domain matters; and uniform convergence of continuous functions preserves continuity of the limit.</p>`,
    worked: { problem: "Show that $f_n(x)=x/n$ converges uniformly to $0$ on $[0,2]$.", skills: ["supremum norm", "epsilon proof", "bounding"], strategy: "Bound the largest possible error on the whole interval, then make that bound small.", steps: [{ do: "Compute the error", result: "$|f_n(x)-0|=x/n$", why: "$x\\ge0$ on the interval" }, { do: "Find the largest error", result: "$\\sup_{0\\le x\\le2}x/n=2/n$", why: "the largest $x$ is $2$" }, { do: "Take the limit", result: "$2/n\\to0$", why: "the global error bound vanishes" }, { do: "Choose $N$", result: "$N>2/\\varepsilon$", why: "then $2/n<\\varepsilon$ for all $n\\ge N$" }], verify: "For $\\varepsilon=0.01$, any $n>200$ makes every error on $[0,2]$ less than $0.01$.", answer: "$f_n\\to0$ uniformly on $[0,2]$.", connects: "Uniform convergence is convergence in the sup norm: one number measures the whole graph error." },
    practice: [
      { problem: "Show $f_n(x)=\\dfrac{\\sin x}{n}$ converges uniformly to $0$ on $\\mathbb{R}$.", steps: [{ do: "Compute the error", result: "$|\\sin x|/n$", why: "subtract the zero limit" }, { do: "Use the sine bound", result: "$|\\sin x|\\le1$", why: "valid for all real inputs" }, { do: "Bound the supremum", result: "$\\sup |f_n(x)|\\le1/n$", why: "same bound works everywhere" }, { do: "Take the limit", result: "$1/n\\to0$", why: "global error shrinks" }], answer: "Uniformly converges to $0$." },
      { problem: "Show $f_n(x)=x^n$ does not converge uniformly to its pointwise limit on $[0,1]$.", steps: [{ do: "Recall the limit", result: "$f(x)=0$ for $x<1$, $f(1)=1$", why: "pointwise result" }, { do: "Choose $x_n=(1/2)^{1/n}$", result: "$x_n<1$", why: "a moving input near $1$" }, { do: "Evaluate the error", result: "$|f_n(x_n)-f(x_n)|=1/2$", why: "the limit below $1$ is zero" }, { do: "Conclude", result: "not uniform", why: "supremum error does not tend to zero" }], answer: "Not uniform on $[0,1]$." },
      { problem: "Test uniform convergence of $f_n(x)=\\dfrac{x}{n+x}$ to $0$ on $[0,10]$.", steps: [{ do: "Compute the error", result: "$x/(n+x)$", why: "nonnegative on the interval" }, { do: "Find its largest value", result: "$x=10$", why: "the expression increases with $x$" }, { do: "Compute the maximum", result: "$10/(n+10)$", why: "substitute endpoint" }, { do: "Take the limit", result: "$10/(n+10)\\to0$", why: "largest error vanishes" }], answer: "Uniform convergence to $0$." },
      { problem: "Show $f_n(x)=\\dfrac{1}{1+nx}$ does not converge uniformly to $0$ on $(0,1]$.", steps: [{ do: "Recall pointwise limit", result: "$0$ for fixed $x>0$", why: "denominator grows" }, { do: "Choose $x_n=1/n$", result: "allowed input", why: "it lies in $(0,1]$" }, { do: "Evaluate", result: "$f_n(1/n)=1/2$", why: "error stays large" }, { do: "Conclude", result: "not uniform", why: "one moving input defeats the global bound" }], answer: "Not uniform on $(0,1]$." },
      { problem: "Use the Weierstrass M-test for $\\sum_{n=1}^{\\infty}\\dfrac{x^n}{n^2}$ on $[-1,1]$.", steps: [{ do: "Bound each term", result: "$|x^n/n^2|\\le1/n^2$", why: "$|x|\\le1$" }, { do: "Check comparison", result: "$\\sum 1/n^2$ converges", why: "$p=2>1$" }, { do: "Apply the M-test", result: "uniform convergence", why: "summable uniform bounds control tails" }, { do: "Interpret", result: "partial sums are uniformly Cauchy", why: "all inputs share one tail bound" }], answer: "Uniform convergence by the M-test." }
    ],
    applications: [
      { title: "Stable approximation errors", background: "Uniform convergence gives one worst-case error bound.", numbers: "If $\\sup |f_n-f|\\le2/n$, then $n=1000$ guarantees error at most $0.002$ everywhere." },
      { title: "Continuity preservation", background: "A uniform limit of continuous functions is continuous.", numbers: "Sup errors $0.1,0.05,0.025$ squeeze the whole graph toward one continuous limit." },
      { title: "Numerical libraries", background: "Function approximations need maximum error guarantees, not just sample checks.", numbers: "A sine approximation with max error $10^{-6}$ on $[-\\pi,\\pi]$ is uniformly accurate over width $6.283$." },
      { title: "Calibration guarantees", background: "A surrogate calibration curve should be close for all scores.", numbers: "If $|\\hat c(p)-c(p)|\\le0.01$ for all $p\\in[0,1]$, every score has at most $1$ percentage point error." },
      { title: "Interchanging integrals", background: "Uniform convergence lets limits pass through integrals on finite intervals.", numbers: "If $\\sup|f_n-f|\\le0.001$ on length $5$, then $|\\int f_n-\\int f|\\le0.005$." },
      { title: "Power-series tails", background: "Uniform tail bounds justify finite polynomials across an interval.", numbers: "For $\\sum x^n$ on $|x|\\le0.5$, the tail after degree $5$ is at most $0.5^6/(1-0.5)=0.03125$." }
    ],
    applicationsClose: "Uniform convergence turns many pointwise promises into one global promise, protecting continuity, integrals, and worst-case error bounds.",
    takeaways: ["Uniform convergence means $\\sup_D |f_n-f|\\to0$.", "One $N$ must work for all inputs.", "Moving counterexample points often show non-uniformity.", "Uniform convergence preserves more structure than pointwise convergence."]
  },

  "math-04-27": {
    id: "math-04-27",
    title: "Power series and analyticity",
    tagline: "A power series is an infinite polynomial, and analyticity means the function is truly equal to such a series nearby.",
    connections: { buildsOn: ["series of functions", "Taylor polynomials", "derivatives"], leadsTo: ["analytic functions", "radius of convergence", "generating functions"], usedWith: ["ratio test", "uniform convergence", "term-by-term differentiation"] },
    motivation: `<p>Polynomials are comfortable: add, differentiate, integrate, and evaluate them with ordinary arithmetic. A <b>power series</b> keeps that comfort while allowing infinitely many terms.</p><p>The beautiful payoff is <b>analyticity</b>. Some functions are not merely approximated by their Taylor series; near a point, they are exactly the sum of that series.</p>`,
    definition: `<p>A power series centered at $a$ is $\\sum_{n=0}^{\\infty} c_n(x-a)^n$. It converges inside a radius $R$, diverges outside that radius, and needs separate endpoint checks. A function is <b>analytic</b> at $a$ if it equals a power series in some interval around $a$.</p><p><b>Assumptions that matter:</b> the radius comes from coefficient growth, often by the ratio test; endpoints are not decided by the radius alone; inside the radius, power series may be differentiated and integrated term by term.</p>`,
    worked: { problem: "Find the radius of convergence for $\\sum_{n=0}^{\\infty}\\dfrac{x^n}{3^n}$ and its sum.", skills: ["geometric power series", "radius of convergence", "sum formula"], strategy: "Treat the series as geometric with ratio $x/3$.", steps: [{ do: "Identify the ratio", result: "$r=x/3$", why: "each term multiplies by $x/3$" }, { do: "Apply convergence", result: "$|x/3|<1$", why: "geometric series require $|r|<1$" }, { do: "Solve", result: "$|x|<3$", why: "radius is $3$ around center $0$" }, { do: "Use the sum formula", result: "$S(x)=\\dfrac{1}{1-x/3}$", why: "sum of $\\sum r^n$" }], verify: "At $x=1.5$, the ratio is $0.5$ and the sum is $2$; at $x=3$, terms equal $1$ and do not approach zero.", answer: "Radius $R=3$; sum $S(x)=1/(1-x/3)$ for $|x|<3$.", connects: "This is the prototype: a power series behaves like an infinite polynomial inside its radius." },
    practice: [
      { problem: "Find the radius of $\\sum_{n=0}^{\\infty} n x^n$.", steps: [{ do: "Use the ratio test", result: "$a_n=nx^n$", why: "coefficients grow linearly" }, { do: "Form the ratio", result: "$\\dfrac{n+1}{n}|x|$", why: "compare consecutive terms" }, { do: "Take the limit", result: "$|x|$", why: "$(n+1)/n\\to1$" }, { do: "Apply the condition", result: "$|x|<1$", why: "ratio limit must be below $1$" }], answer: "Radius $R=1$." },
      { problem: "Find the radius of $\\sum_{n=0}^{\\infty}\\dfrac{x^n}{n!}$.", steps: [{ do: "Form the ratio", result: "$\\left|\\dfrac{x^{n+1}/(n+1)!}{x^n/n!}\\right|$", why: "ratio test" }, { do: "Cancel", result: "$\\dfrac{|x|}{n+1}$", why: "$n!/(n+1)!=1/(n+1)$" }, { do: "Take the limit", result: "$0$", why: "for every fixed $x$" }, { do: "Conclude", result: "$R=\\infty$", why: "the test succeeds for all real $x$" }], answer: "Radius is infinite." },
      { problem: "Use the first four terms of $e^x$ to approximate $e^{0.2}$.", steps: [{ do: "Write terms", result: "$1+x+x^2/2+x^3/6$", why: "Maclaurin series for $e^x$" }, { do: "Substitute", result: "$1+0.2+0.04/2+0.008/6$", why: "evaluate at $0.2$" }, { do: "Simplify", result: "$1.22133\\ldots$", why: "add the four terms" }, { do: "Compare", result: "$e^{0.2}\\approx1.22140$", why: "the approximation is close" }], answer: "Approximately $1.22133$." },
      { problem: "Find the interval of convergence for $\\sum_{n=1}^{\\infty}\\dfrac{x^n}{n}$.", steps: [{ do: "Use the ratio test", result: "$\\left|\\dfrac{x^{n+1}/(n+1)}{x^n/n}\\right|\\to |x|$", why: "$n/(n+1)\\to1$" }, { do: "Get the radius", result: "$|x|<1$", why: "ratio below $1$" }, { do: "Check $x=1$", result: "$\\sum1/n$ diverges", why: "harmonic series" }, { do: "Check $x=-1$", result: "$\\sum(-1)^n/n$ converges", why: "alternating harmonic series" }], answer: "Interval $[-1,1)$." },
      { problem: "Differentiate $\\sum_{n=0}^{\\infty}x^n=1/(1-x)$ term by term for $|x|<1$.", steps: [{ do: "Differentiate the left side", result: "$\\sum_{n=1}^{\\infty}n x^{n-1}$", why: "power rule" }, { do: "Differentiate the right side", result: "$1/(1-x)^2$", why: "chain rule" }, { do: "Equate", result: "$\\sum_{n=1}^{\\infty}n x^{n-1}=\\dfrac{1}{(1-x)^2}$", why: "valid inside radius" }, { do: "Check at $x=0.5$", result: "$4$", why: "$1/(0.5)^2=4$" }], answer: "$\\sum_{n=1}^{\\infty}n x^{n-1}=1/(1-x)^2$ for $|x|<1$." }
    ],
    applications: [
      { title: "Fast elementary functions", background: "Computers evaluate functions with polynomial pieces derived from power series.", numbers: "For $\\sin(0.1)$, $0.1-0.1^3/6=0.0998333$, matching the true value to about $8$ decimal places." },
      { title: "Analytic loss approximations", background: "Near a smooth minimum, Taylor series explain quadratic approximations.", numbers: "If $L(w)=L(0)+3w^2+2w^3+\\cdots$, then at $w=0.1$ the cubic term is $0.002$ and the quadratic term is $0.03$." },
      { title: "Generating functions", background: "Combinatorics stores sequences as coefficients of power series.", numbers: "$1+x+x^2+\\cdots$ has coefficient $1$ for every count and sums to $1.25$ at $x=0.2$." },
      { title: "Moment generating functions", background: "Probability uses analytic functions to encode moments by derivatives at zero.", numbers: "For $M(t)=e^{2t}$, $M'(0)=2$ and $M''(0)=4$." },
      { title: "Activation local behavior", background: "Smooth activations have local series that explain near-linear behavior.", numbers: "The sigmoid near $0$ is $0.5+x/4+\\cdots$; at $x=0.2$ this gives $0.55$, close to $0.5498$." },
      { title: "Error control", background: "Power-series remainders give concrete accuracy guarantees.", numbers: "For $e^{0.1}$ after terms through $x^3/6$, the next term is $0.1^4/24\\approx0.00000417$." }
    ],
    applicationsClose: "Power series make infinite processes feel polynomial, and analyticity tells us when that polynomial language exactly matches the function nearby.",
    takeaways: ["A power series has the form $\\sum c_n(x-a)^n$.", "The radius of convergence is often found with ratio or root tests.", "Endpoints require separate checks.", "Inside the radius, power series can be differentiated and integrated term by term."]
  },

  "math-04-28": {
    id: "math-04-28",
    title: "Metric spaces",
    tagline: "A metric space is any world where distance obeys the rules needed for convergence to make sense.",
    connections: { buildsOn: ["sets", "absolute value", "vectors"], leadsTo: ["open and closed sets", "compactness", "contraction mapping theorem"], usedWith: ["norms", "Cauchy sequences", "continuity"] },
    motivation: `<p>You already trust distance on the real line: $|x-y|$ says how far two numbers are. A metric space keeps the useful rules of distance and lets the objects be vectors, functions, strings, distributions, or model parameters.</p><p>Once distance is defined, familiar ideas return: points can approach, sequences can converge, and maps can be continuous.</p>`,
    definition: `<p>A <b>metric space</b> is a set $X$ together with a distance function $d:X\\times X\\to[0,\\infty)$ such that for all $x,y,z\\in X$: $d(x,y)=0$ exactly when $x=y$; $d(x,y)=d(y,x)$; and $d(x,z)\\le d(x,y)+d(y,z)$. The last rule is the triangle inequality.</p><p><b>Assumptions that matter:</b> the metric must be chosen and stated; different metrics on the same set can define different notions of closeness; and convergence means $d(x_n,x)\\to0$ in the chosen metric.</p>`,
    worked: { problem: "Verify the triangle inequality for $d(x,y)=|x-y|$ using $x=2$, $y=5$, $z=9$.", skills: ["absolute value distance", "metric axioms", "triangle inequality"], strategy: "Compute all three distances and compare direct distance with the two-leg path.", steps: [{ do: "Compute $d(x,z)$", result: "$d(2,9)=|2-9|=7$", why: "direct distance" }, { do: "Compute $d(x,y)$", result: "$d(2,5)=3$", why: "first leg" }, { do: "Compute $d(y,z)$", result: "$d(5,9)=4$", why: "second leg" }, { do: "Compare", result: "$7\\le3+4=7$", why: "the direct route is no longer than going through $y$" }], verify: "Equality holds because the three points lie in order on the real line.", answer: "The triangle inequality holds in this numerical case.", connects: "Metric spaces abstract the reliable behavior of distance." },
    practice: [
      { problem: "In $\\mathbb{R}^2$ with Euclidean distance, find $d((1,2),(4,6))$.", steps: [{ do: "Subtract coordinates", result: "$(3,4)$", why: "distance depends on displacement" }, { do: "Square components", result: "$3^2+4^2=25$", why: "Euclidean distance uses sum of squares" }, { do: "Take square root", result: "$\\sqrt{25}=5$", why: "Pythagorean theorem" }, { do: "State distance", result: "$5$", why: "a $3$-$4$-$5$ triangle" }], answer: "$5$." },
      { problem: "With metric $d_1(x,y)=|x_1-y_1|+|x_2-y_2|$, find distance from $(1,2)$ to $(4,6)$.", steps: [{ do: "First coordinate", result: "$|1-4|=3$", why: "horizontal move" }, { do: "Second coordinate", result: "$|2-6|=4$", why: "vertical move" }, { do: "Add", result: "$3+4=7$", why: "Manhattan metric" }, { do: "Compare", result: "$7>5$", why: "different metrics give different distances" }], answer: "$7$." },
      { problem: "For vectors $a=(1,0,2)$ and $b=(1,3,-1)$, compute $d_\\infty(a,b)$.", steps: [{ do: "Compute coordinate gaps", result: "$0,3,3$", why: "absolute differences" }, { do: "Take the maximum", result: "$3$", why: "sup distance uses largest error" }, { do: "State value", result: "$d_\\infty(a,b)=3$", why: "one coordinate controls the distance" }, { do: "Interpret", result: "all coordinates differ by at most $3$", why: "the sup-norm promise" }], answer: "$3$." },
      { problem: "Show $x_n=1/n$ converges to $0$ in the usual metric.", steps: [{ do: "Write distance", result: "$d(x_n,0)=|1/n-0|$", why: "convergence is distance to the limit" }, { do: "Simplify", result: "$1/n$", why: "positive term" }, { do: "Take limit", result: "$1/n\\to0$", why: "standard sequence" }, { do: "Conclude", result: "$x_n\\to0$", why: "distance vanishes" }], answer: "$1/n\\to0$, so $x_n\\to0$." },
      { problem: "For functions on $[0,1]$ with $d(f,g)=\\sup|f-g|$, compute distance between $f(x)=x$ and $g(x)=x^2$.", steps: [{ do: "Write gap", result: "$|x-x^2|=x-x^2$", why: "nonnegative on $[0,1]$" }, { do: "Differentiate gap", result: "$1-2x$", why: "find maximum" }, { do: "Set derivative zero", result: "$x=1/2$", why: "critical point" }, { do: "Evaluate", result: "$1/2-1/4=1/4$", why: "endpoint gaps are zero" }], answer: "$d(f,g)=1/4$." }
    ],
    applications: [
      { title: "Nearest-neighbor search", background: "Classifiers and retrieval systems depend on a chosen metric.", numbers: "Point $(1,2)$ is distance $5$ from $(4,6)$ in Euclidean metric but $7$ in Manhattan metric." },
      { title: "Embedding similarity", background: "Vector databases turn similarity into distance for ranking.", numbers: "Unit vectors with cosine similarity $0.8$ have Euclidean distance $\\sqrt{2-2(0.8)}\\approx0.632$." },
      { title: "Function approximation", background: "Uniform error is a metric on bounded functions.", numbers: "If $\\sup|f-g|=0.02$, every prediction of $g$ is within $0.02$ of $f$." },
      { title: "Edit distance", background: "Computer science uses metrics beyond geometry, such as string distances.", numbers: "The words 'cat' and 'cut' have edit distance $1$ by replacing $a$ with $u$." },
      { title: "Distribution distance", background: "ML objectives compare probability distributions with distance-like quantities.", numbers: "For $p=(0.2,0.8)$ and $q=(0.5,0.5)$, $L^1$ distance is $0.6$." },
      { title: "Optimization stopping", background: "Convergence of iterates is measured by a distance between parameters.", numbers: "If $\\|w_{t+1}-w_t\\|_2=0.001$ and tolerance is $0.005$, the step-size test passes." }
    ],
    applicationsClose: "A metric is the quiet infrastructure under convergence: once distance is honest, limits and continuity can be discussed in many worlds.",
    takeaways: ["A metric is a nonnegative, symmetric distance with identity and triangle inequality.", "The chosen metric defines what close means.", "Convergence means distance to the proposed limit tends to zero.", "Vectors, functions, strings, and distributions can all live in metric spaces."]
  },

  "math-04-29": {
    id: "math-04-29",
    title: "Open and closed sets",
    tagline: "Open sets contain wiggle room around every point; closed sets contain their boundary limits.",
    connections: { buildsOn: ["metric spaces", "balls", "sequences"], leadsTo: ["compactness", "continuity in metric spaces", "optimization on feasible sets"], usedWith: ["neighborhoods", "boundaries", "limits of sequences"] },
    motivation: `<p>On the real line, $(0,1)$ feels different from $[0,1]$. The first lets every point wiggle a little without leaving; the second includes the endpoints where the interval stops.</p><p><b>Open</b> and <b>closed</b> sets turn that feeling into metric-space language. They tell us where local arguments are safe and where limiting sequences stay inside.</p>`,
    definition: `<p>In a metric space, the open ball of radius $r$ around $x$ is $B(x,r)=\\{y:d(x,y)<r\\}$. A set $U$ is <b>open</b> if every $x\\in U$ has some ball $B(x,r)$ contained in $U$. A set $C$ is <b>closed</b> if every convergent sequence from $C$ has its limit in $C$.</p><p><b>Assumptions that matter:</b> openness and closedness depend on the metric and ambient space; a set can be both open and closed; and a set can be neither open nor closed.</p>`,
    worked: { problem: "Decide whether $(0,1)$ and $[0,1]$ are open or closed in $\\mathbb{R}$.", skills: ["neighborhoods", "sequence limits", "interval endpoints"], strategy: "Check wiggle room for openness and endpoint limits for closedness.", steps: [{ do: "Test $(0,1)$ for openness", result: "$r<\\min(x,1-x)$ works", why: "a small interval around $x$ stays inside" }, { do: "Test $(0,1)$ for closedness", result: "$1/n\\in(0,1)$ but $1/n\\to0$", why: "the limit $0$ is missing" }, { do: "Test $[0,1]$ for openness", result: "$0$ has no positive-radius real ball inside", why: "balls around $0$ include negative points" }, { do: "Test $[0,1]$ for closedness", result: "limits of sequences in $[0,1]$ stay in $[0,1]$", why: "the interval includes endpoints" }], verify: "The two intervals differ exactly at boundary behavior: wiggle room versus containing limits.", answer: "$(0,1)$ is open not closed; $[0,1]$ is closed not open in $\\mathbb{R}$.", connects: "Open sets support local movement; closed sets support limit-taking." },
    practice: [
      { problem: "Is $(0,1]$ open, closed, both, or neither in $\\mathbb{R}$?", steps: [{ do: "Check openness at $1$", result: "small balls around $1$ include points above $1$", why: "those points leave the set" }, { do: "Conclude not open", result: "not open", why: "one point lacks wiggle room" }, { do: "Check closedness at $0$", result: "$1/n\\in(0,1]$ and $1/n\\to0$", why: "sequence stays in the set" }, { do: "Observe the limit", result: "$0\\notin(0,1]$", why: "missing limit breaks closedness" }], answer: "Neither open nor closed." },
      { problem: "Show $\\{x:|x-2|<0.5\\}$ is open in $\\mathbb{R}$.", steps: [{ do: "Rewrite", result: "$1.5<x<2.5$", why: "absolute value is distance from $2$" }, { do: "Pick $x$ in the set", result: "$x\\in(1.5,2.5)$", why: "arbitrary interior point" }, { do: "Choose radius", result: "$r<\\min(x-1.5,2.5-x)$", why: "stay away from endpoints" }, { do: "Conclude", result: "$B(x,r)$ stays inside", why: "every point has wiggle room" }], answer: "Open." },
      { problem: "Is $\\{0\\}\\cup[1,2]$ closed in $\\mathbb{R}$?", steps: [{ do: "Identify pieces", result: "$\\{0\\}$ and $[1,2]$", why: "both include boundary points" }, { do: "Find possible clusters", result: "$0$ or points in $[1,2]$", why: "there is a gap between $0$ and $1$" }, { do: "Check inclusion", result: "all possible limits are included", why: "no boundary is missing" }, { do: "Conclude", result: "closed", why: "no sequence limit escapes" }], answer: "Closed." },
      { problem: "In the subspace $X=[0,1]$, is $[0,0.2)$ open relative to $X$?", steps: [{ do: "Use ambient space", result: "$X=[0,1]$", why: "openness is relative" }, { do: "Write intersection", result: "$[0,0.2)=X\\cap(-0.1,0.2)$", why: "intersect an open real interval with $X$" }, { do: "Apply subspace rule", result: "open in $X$", why: "relative balls cannot go outside $X$" }, { do: "Contrast", result: "not open in $\\mathbb{R}$", why: "a real ball around $0$ includes negatives" }], answer: "Open in $[0,1]$, not open in $\\mathbb{R}$." },
      { problem: "Show $\\{x:x^2\\le4\\}$ is closed in $\\mathbb{R}$.", steps: [{ do: "Solve inequality", result: "$-2\\le x\\le2$", why: "square at most $4$" }, { do: "Recognize interval", result: "$[-2,2]$", why: "closed interval" }, { do: "Use sequence criterion", result: "limits preserve $-2\\le x_n\\le2$", why: "order is preserved under limits" }, { do: "Conclude", result: "closed", why: "all limits remain inside" }], answer: "Closed." }
    ],
    applications: [
      { title: "Feasible regions", background: "Optimization constraints may be open or closed, affecting whether optima are attained.", numbers: "Minimize $x$ over $(0,1)$ has infimum $0$ but no minimizer; over $[0,1]$, the minimum is $0$." },
      { title: "Safe parameter ranges", background: "Strict inequalities create open sets with room for perturbation.", numbers: "If $0<\\eta<0.1$, then $\\eta=0.05$ has margin $0.05$ to each boundary." },
      { title: "Clipping constraints", background: "Closed intervals are common in bounded numerical systems.", numbers: "A probability clipped to $[0,1]$ can converge to $0$ or $1$ and remain allowed." },
      { title: "Decision boundaries", background: "Classification regions depend on whether the threshold is included.", numbers: "Accept if $s\\ge0.7$ gives region $[0.7,1]$, including score $0.700$." },
      { title: "Robustness margins", background: "Open balls formalize perturbations that stay within a property.", numbers: "Certified radius $0.03$ in $L^\\infty$ means max pixel change below $0.03$ stays in the guarantee set." },
      { title: "Limit closure in algorithms", background: "Closed feasible sets keep convergent iterates feasible in the limit.", numbers: "If every iterate has norm at most $1$ and $w_t\\to w$, then closedness gives $\\|w\\|\\le1$." }
    ],
    applicationsClose: "Open sets are about local freedom; closed sets are about safe limits. Analysis and ML guarantees need both ideas at the right moment.",
    takeaways: ["Open means every point contains a small ball inside the set.", "Closed means limits of convergent sequences from the set stay in the set.", "The ambient metric space matters.", "A set may be open, closed, both, or neither."]
  },

  "math-04-30": {
    id: "math-04-30",
    title: "Compactness",
    tagline: "Compactness is the finite-control principle: infinitely many possibilities can be managed by finitely many local pieces.",
    connections: { buildsOn: ["open and closed sets", "boundedness", "sequences"], leadsTo: ["existence of maxima and minima", "uniform continuity", "fixed-point theorems"], usedWith: ["closed intervals", "subsequences", "optimization"] },
    motivation: `<p>Closed intervals like $[0,1]$ have a comforting property: continuous functions reach their maximum and minimum there. Open intervals like $(0,1)$ do not always behave so kindly.</p><p><b>Compactness</b> is the deep reason. It says the set is small enough and complete enough that infinite searching cannot escape to a missing edge or infinity.</p>`,
    definition: `<p>In $\\mathbb{R}^n$, the Heine-Borel theorem says a set is <b>compact</b> exactly when it is closed and bounded. Sequentially, compactness means every sequence in the set has a convergent subsequence whose limit is still in the set.</p><p><b>Assumptions that matter:</b> closed and bounded characterizes compactness in finite-dimensional Euclidean spaces, not every metric space; compactness is relative to the metric; and continuous functions on compact sets attain maxima and minima.</p>`,
    worked: { problem: "Show that $[0,2]$ is compact and use it to find the maximum of $f(x)=x(2-x)$.", skills: ["closed and bounded", "critical points", "extreme value theorem"], strategy: "Use Heine-Borel for compactness, then check endpoints and critical points.", steps: [{ do: "Check closedness", result: "$[0,2]$ contains endpoints", why: "closed interval" }, { do: "Check boundedness", result: "$0\\le x\\le2$", why: "finite bounds" }, { do: "Differentiate", result: "$f'(x)=2-2x$", why: "find interior candidates" }, { do: "Solve", result: "$x=1$", why: "critical point" }, { do: "Evaluate", result: "$f(0)=0$, $f(1)=1$, $f(2)=0$", why: "compare candidates" }], verify: "The parabola opens downward, so the middle value should be highest.", answer: "$[0,2]$ is compact; the maximum is $1$ at $x=1$.", connects: "Compactness turns continuous optimization from a hope into a guarantee." },
    practice: [
      { problem: "Is $(0,1)$ compact in $\\mathbb{R}$?", steps: [{ do: "Check boundedness", result: "bounded", why: "all points lie between $0$ and $1$" }, { do: "Check closedness", result: "not closed", why: "endpoints are missing" }, { do: "Use Heine-Borel", result: "not compact", why: "compact subsets of $\\mathbb{R}$ are closed and bounded" }, { do: "Give a sequence", result: "$1/n\\in(0,1)$ and $1/n\\to0$", why: "the limit is missing" }], answer: "Not compact." },
      { problem: "Is $\\{1/n:n\\ge1\\}\\cup\\{0\\}$ compact in $\\mathbb{R}$?", steps: [{ do: "Check boundedness", result: "contained in $[0,1]$", why: "finite bounds" }, { do: "Find accumulation point", result: "$0$", why: "$1/n$ clusters at zero" }, { do: "Observe inclusion", result: "$0$ is included", why: "no limit point is missing" }, { do: "Conclude", result: "compact", why: "closed and bounded in $\\mathbb{R}$" }], answer: "Compact." },
      { problem: "Find the minimum of $f(x)=x^2-4x+5$ on $[0,5]$.", steps: [{ do: "Use compactness", result: "$[0,5]$ is compact", why: "continuous functions attain extrema" }, { do: "Differentiate", result: "$f'(x)=2x-4$", why: "critical point test" }, { do: "Solve", result: "$x=2$", why: "interior candidate" }, { do: "Evaluate", result: "$f(0)=5$, $f(2)=1$, $f(5)=10$", why: "compare candidates" }], answer: "Minimum $1$ at $x=2$." },
      { problem: "Show $[0,\\infty)$ is not compact in $\\mathbb{R}$.", steps: [{ do: "Check closedness", result: "closed", why: "it contains its endpoint" }, { do: "Check boundedness", result: "not bounded", why: "values grow without limit" }, { do: "Use Heine-Borel", result: "not compact", why: "compact needs closed and bounded" }, { do: "Give a sequence", result: "$x_n=n$", why: "no subsequence converges to a finite point" }], answer: "Not compact." },
      { problem: "Why does $f(x)=1/x$ fail to attain a maximum on $(0,1]$?", steps: [{ do: "Check the domain", result: "$(0,1]$", why: "not closed because $0$ is missing" }, { do: "Observe behavior", result: "$1/x\\to\\infty$ as $x\\to0^+$", why: "values escape near the missing boundary" }, { do: "Check a finite point", result: "$f(1)=1$", why: "this is not the largest value" }, { do: "Conclude", result: "no maximum", why: "compactness is missing" }], answer: "No maximum is attained." }
    ],
    applications: [
      { title: "Existence of optima", background: "Continuous losses on compact parameter sets have minimizers.", numbers: "For $L(w)=(w-2)^2$ on $[-1,1]$, the minimum is at $w=1$ with loss $1$." },
      { title: "Hyperparameter boxes", background: "Search often restricts parameters to compact intervals.", numbers: "Learning rate in $[10^{-4},10^{-1}]$ and weight decay in $[0,0.1]$ form a closed bounded rectangle." },
      { title: "Uniform continuity", background: "Continuous functions on compact sets cannot change arbitrarily suddenly.", numbers: "For $f(x)=x^2$ on $[0,3]$, $|f'(x)|\\le6$, so a $0.01$ move changes output by at most about $0.06$." },
      { title: "Subsequence extraction", background: "Compactness guarantees bounded histories have convergent subsequences.", numbers: "A sequence of weights in $[-5,5]$ has some convergent subsequence." },
      { title: "Certified verification", background: "Finite coverings of compact domains support interval arithmetic.", numbers: "Cover $[0,1]$ by intervals of width $0.1$; only $10$ intervals are needed." },
      { title: "Probability simplex", background: "Finite-dimensional probability vectors form compact feasible sets.", numbers: "For two classes, $p\\in[0,1]$; entropy is maximized at $p=0.5$ with value $\\ln2\\approx0.693$." }
    ],
    applicationsClose: "Compactness is why finite-dimensional continuous optimization can make existence promises instead of chasing escaping sequences forever.",
    takeaways: ["In $\\mathbb{R}^n$, compact means closed and bounded.", "Every sequence in a compact set has a convergent subsequence with limit in the set.", "Continuous functions on compact sets attain maxima and minima.", "Missing boundaries or unbounded directions often break compactness."]
  },

  "math-04-31": {
    id: "math-04-31",
    title: "The contraction mapping theorem",
    tagline: "A contraction pulls points closer together, so repeated application must settle at one fixed point.",
    connections: { buildsOn: ["metric spaces", "complete spaces", "fixed points"], leadsTo: ["fixed-point iteration", "gradient method guarantees", "Banach spaces"], usedWith: ["Lipschitz constants", "Cauchy sequences", "iterative solvers"] },
    motivation: `<p>Many algorithms repeat the same update: start with $x_0$, compute $x_1=T(x_0)$, then keep going. The natural question is whether this settles.</p><p>The contraction mapping theorem gives a practical answer. If the update always shrinks distances by a fixed factor below $1$, then all paths lead to one fixed point.</p>`,
    definition: `<p>A map $T$ on a metric space $(X,d)$ is a <b>contraction</b> if there is a constant $0\\le q<1$ such that $d(Tx,Ty)\\le qd(x,y)$ for all $x,y\\in X$. If $X$ is complete and $T$ maps $X$ into itself, then $T$ has a unique fixed point $x^*$ with $T(x^*)=x^*$, and $x_{k+1}=T(x_k)$ converges to $x^*$ from any start.</p><p><b>Assumptions that matter:</b> completeness is essential; the map must send the space into itself; and the Lipschitz constant must be strictly less than $1$.</p>`,
    worked: { problem: "Use the theorem for $T(x)=0.5x+1$ on $\\mathbb{R}$ and start $x_0=0$.", skills: ["Lipschitz constants", "fixed points", "iteration"], strategy: "Show the update halves distances, solve the fixed-point equation, and watch the iterates approach it.", steps: [{ do: "Compute distance after applying $T$", result: "$|T(x)-T(y)|=|0.5x+1-(0.5y+1)|$", why: "subtract outputs" }, { do: "Simplify", result: "$0.5|x-y|$", why: "the constant cancels" }, { do: "Identify the factor", result: "$q=0.5$", why: "strictly below $1$" }, { do: "Solve fixed point", result: "$x=0.5x+1$ gives $x=2$", why: "$T(x)=x$" }, { do: "Iterate from $0$", result: "$0,1,1.5,1.75,1.875$", why: "values move toward $2$" }], verify: "The error halves each step: $2$, $1$, $0.5$, $0.25$.", answer: "Unique fixed point $x^*=2$, and iteration converges to it.", connects: "This is the model for many convergence proofs: shrink distances, then convergence follows." },
    practice: [
      { problem: "For $T(x)=0.8x+3$, find the contraction factor and fixed point.", steps: [{ do: "Compute distance", result: "$|T(x)-T(y)|=0.8|x-y|$", why: "linear part controls distances" }, { do: "Identify $q$", result: "$0.8<1$", why: "contraction" }, { do: "Solve fixed point", result: "$x=0.8x+3$", why: "set $T(x)=x$" }, { do: "Isolate", result: "$0.2x=3$, so $x=15$", why: "divide by $0.2$" }], answer: "$q=0.8$, fixed point $15$." },
      { problem: "Iterate $x_{k+1}=0.25x_k+6$ from $x_0=0$ for three steps and find the limit.", steps: [{ do: "Compute $x_1$", result: "$6$", why: "$0.25\\cdot0+6$" }, { do: "Compute $x_2$", result: "$7.5$", why: "$0.25\\cdot6+6$" }, { do: "Compute $x_3$", result: "$7.875$", why: "$0.25\\cdot7.5+6$" }, { do: "Solve fixed point", result: "$x=0.25x+6$ gives $x=8$", why: "iteration approaches fixed point" }], answer: "Steps $6,7.5,7.875$; limit $8$." },
      { problem: "Show $T(x)=x+1$ is not a contraction on $\\mathbb{R}$.", steps: [{ do: "Compute distance", result: "$|T(x)-T(y)|=|x+1-y-1|$", why: "compare outputs" }, { do: "Simplify", result: "$|x-y|$", why: "distance is unchanged" }, { do: "Identify best constant", result: "$q=1$", why: "not strictly less than $1$" }, { do: "Conclude", result: "not a contraction", why: "the theorem cannot apply" }], answer: "Not a contraction." },
      { problem: "For $T(x)=\\cos x$ on $[0,1]$, use $|\\sin x|\\le\\sin1\\approx0.842$ to explain contraction.", steps: [{ do: "Use derivative bound", result: "$|T'(x)|=|\\sin x|\\le0.842$", why: "mean value theorem gives a Lipschitz bound" }, { do: "Set $q$", result: "$q=0.842<1$", why: "strict contraction" }, { do: "Check mapping", result: "$\\cos([0,1])\\subset[\\cos1,1]\\subset[0,1]$", why: "the interval maps into itself" }, { do: "Apply theorem", result: "unique fixed point", why: "complete interval plus contraction" }], answer: "There is a unique fixed point in $[0,1]$." },
      { problem: "If a contraction has $q=0.6$ and initial error $5$, bound error after $4$ steps.", steps: [{ do: "Use error bound", result: "$|x_k-x^*|\\le q^k|x_0-x^*|$", why: "errors shrink geometrically" }, { do: "Substitute", result: "$0.6^4\\cdot5$", why: "four steps" }, { do: "Compute power", result: "$0.1296$", why: "multiply four factors" }, { do: "Multiply", result: "$0.648$", why: "final bound" }], answer: "At most $0.648$." }
    ],
    applications: [
      { title: "Fixed-point solvers", background: "Nonlinear equations are often rewritten as $x=T(x)$ and iterated.", numbers: "For $T(x)=0.5x+1$, an initial error $2$ is at most $2/1024\\approx0.00195$ after $10$ steps." },
      { title: "Dynamic programming", background: "Bellman operators with discount are contractions under the sup norm.", numbers: "With discount $\\gamma=0.9$, value-iteration errors shrink by at most $10\\%$ each step relative to the previous bound." },
      { title: "Iterative linear solvers", background: "Linear updates converge when their iteration matrix shrinks distances.", numbers: "If an update matrix has norm $0.4$, error $1.0$ becomes at most $0.4$, then $0.16$, then $0.064$." },
      { title: "Implicit neural layers", background: "Deep equilibrium models define activations as fixed points of a layer map.", numbers: "A layer with Lipschitz constant $0.7$ reduces a $3$-unit hidden-state error to at most $3(0.7)^5\\approx0.504$." },
      { title: "Policy evaluation", background: "RL value functions satisfy contraction equations because future rewards are discounted.", numbers: "With $\\gamma=0.95$, an error bound $1$ contracts to $0.95^{20}\\approx0.358$ after $20$ iterations." },
      { title: "Stability warnings", background: "Showing an update is not a contraction warns of stall or divergence.", numbers: "$T(x)=1.05x$ expands distance $2$ to $2.1$, so errors grow by $5\\%$ per step." }
    ],
    applicationsClose: "The contraction theorem is convergence made visible: shrink distance by a fixed ratio, and the algorithm has one destination plus a geometric error clock.",
    takeaways: ["A contraction satisfies $d(Tx,Ty)\\le qd(x,y)$ with $q<1$.", "On a complete space, a contraction has a unique fixed point.", "Iterating the contraction converges from any starting point.", "The error shrinks geometrically, roughly like $q^k$."]
  },

  "math-04-32": {
    id: "math-04-32",
    title: "Convergence guarantees for gradient methods",
    tagline: "Gradient methods converge when smoothness, curvature, and step size turn an update into a controlled fixed-point process.",
    connections: { buildsOn: ["gradients", "Lipschitz constants", "contraction mapping theorem"], leadsTo: ["convex optimization", "stochastic gradient methods", "deep-learning training analysis"], usedWith: ["strong convexity", "smoothness", "fixed-point iteration"] },
    motivation: `<p>Gradient descent feels simple: move downhill by $w_{k+1}=w_k-\\eta\\nabla f(w_k)$. The serious question is why this repeated move should converge instead of bounce, crawl, or explode.</p><p>The capstone idea is that assumptions turn the update into a reliable map. Smoothness limits how quickly gradients can change; curvature keeps the minimizer identifiable; and the learning rate controls whether the update is a contraction.</p>`,
    definition: `<p>Gradient descent uses $w_{k+1}=T(w_k)=w_k-\\eta\\nabla f(w_k)$. For a one-dimensional quadratic $f(w)=\\frac{a}{2}(w-w^*)^2$, the update is $w_{k+1}-w^*=(1-\\eta a)(w_k-w^*)$, so it is a contraction exactly when $|1-\\eta a|<1$. More generally, $L$-Lipschitz gradients and $\\mu$-strong convexity give standard linear-rate guarantees for suitable $\\eta$.</p><p><b>Assumptions that matter:</b> smoothness means gradients are not changing too abruptly; strong convexity gives a single well-conditioned minimizer; step size must respect the largest curvature; stochastic gradients add noise and require smaller or decaying steps for exact convergence.</p>`,
    worked: { problem: "For $f(w)=\\frac12\\cdot4(w-3)^2$, run gradient descent with $\\eta=0.2$ from $w_0=0$ and prove contraction.", skills: ["quadratic gradients", "contraction factors", "gradient descent updates"], strategy: "Compute the update map, read its contraction factor, then iterate numerically.", steps: [{ do: "Compute the gradient", result: "$f'(w)=4(w-3)$", why: "differentiate the quadratic" }, { do: "Write the update", result: "$w_{k+1}=w_k-0.2\\cdot4(w_k-3)$", why: "gradient descent formula" }, { do: "Simplify the map", result: "$w_{k+1}=0.2w_k+2.4$", why: "$1-0.8=0.2$ and $0.8\\cdot3=2.4$" }, { do: "Find the fixed point", result: "$w=0.2w+2.4$ gives $w=3$", why: "the minimizer is the fixed point" }, { do: "Read contraction factor", result: "$q=0.2$", why: "distances to the fixed point shrink by factor $0.2$" }, { do: "Compute iterates", result: "$w_1=2.4$, $w_2=2.88$, $w_3=2.976$", why: "weights approach $3$ quickly" }], verify: "Errors are $3$, $0.6$, $0.12$, $0.024$, exactly multiplying by $0.2$ each step.", answer: "The update is a contraction with factor $0.2$ and converges linearly to $w^*=3$.", connects: "Gradient descent on a well-behaved quadratic is fixed-point iteration with a visible contraction factor." },
    practice: [
      { problem: "For $f(w)=\\frac12\\cdot10w^2$, what step sizes make gradient descent a contraction?", steps: [{ do: "Compute gradient", result: "$f'(w)=10w$", why: "quadratic curvature is $10$" }, { do: "Write error update", result: "$w_{k+1}=(1-10\\eta)w_k$", why: "minimizer is $0$" }, { do: "Require contraction", result: "$|1-10\\eta|<1$", why: "error factor magnitude below $1$" }, { do: "Solve", result: "$0<\\eta<0.2$", why: "subtract and divide" }], answer: "$0<\\eta<0.2$." },
      { problem: "Run two steps on $f(w)=(w-5)^2$ with $\\eta=0.1$ from $w_0=1$.", steps: [{ do: "Compute gradient", result: "$f'(w)=2(w-5)$", why: "chain rule" }, { do: "Evaluate at $w_0=1$", result: "$f'(1)=-8$", why: "current point is left of minimizer" }, { do: "Update once", result: "$w_1=1-0.1(-8)=1.8$", why: "move opposite gradient" }, { do: "Evaluate next gradient", result: "$f'(1.8)=-6.4$", why: "still left of $5$" }, { do: "Update twice", result: "$w_2=1.8-0.1(-6.4)=2.44$", why: "closer to minimizer" }], answer: "$w_1=1.8$, $w_2=2.44$." },
      { problem: "For $f(w)=5w^2$, show why $\\eta=0.25$ diverges.", steps: [{ do: "Compute gradient", result: "$f'(w)=10w$", why: "curvature factor" }, { do: "Write update", result: "$w_{k+1}=w_k-0.25(10w_k)$", why: "gradient descent" }, { do: "Simplify", result: "$w_{k+1}=-1.5w_k$", why: "error multiplier" }, { do: "Check magnitude", result: "$|-1.5|>1$", why: "distances grow" }, { do: "Give example", result: "$w_0=1$, $w_1=-1.5$, $w_2=2.25$", why: "oscillation expands" }], answer: "It diverges because the error multiplier has magnitude $1.5$." },
      { problem: "A gradient map has contraction factor $q=0.8$ and initial distance $10$. Bound distance after $15$ steps.", steps: [{ do: "Use geometric error", result: "$d_k\\le q^k d_0$", why: "contraction bound" }, { do: "Substitute", result: "$d_{15}\\le0.8^{15}\\cdot10$", why: "fifteen steps" }, { do: "Compute", result: "$0.8^{15}\\approx0.0352$", why: "repeated multiplication" }, { do: "Multiply", result: "$0.352$", why: "final distance bound" }], answer: "At most about $0.352$." },
      { problem: "For a smooth convex function with $L=20$, choose a safe fixed step and explain the descent condition.", steps: [{ do: "Use safe rule", result: "$\\eta\\le1/L$", why: "smooth convex descent guarantee" }, { do: "Substitute $L=20$", result: "$\\eta\\le0.05$", why: "reciprocal of gradient-change rate" }, { do: "Choose concrete step", result: "$\\eta=0.04$", why: "strictly below the bound" }, { do: "State meaning", result: "loss decreases under the standard smoothness inequality", why: "the quadratic upper bound is controlled" }], answer: "A safe choice is $\\eta=0.04$; $0.05$ is the $1/L$ boundary." }
    ],
    applications: [
      { title: "Why gradient descent converges on a quadratic", background: "A positive quadratic has a linear gradient, so the algorithm is exactly fixed-point iteration.", numbers: "For curvature $a=4$ and $\\eta=0.2$, the error factor is $|1-0.8|=0.2$; error $3$ becomes $0.6$, then $0.12$." },
      { title: "Learning-rate upper bounds", background: "Smoothness limits how aggressive a step can be before overshooting dominates descent.", numbers: "If largest curvature is $L=50$, the simple safe step $1/L$ is $0.02$; step $0.1$ is five times larger." },
      { title: "Strong convexity gives linear rates", background: "Strong convexity prevents flat valleys and gives a unique minimizer with geometric decay.", numbers: "With $L=10$, $\\mu=2$, step $1/L=0.1$ gives factor $1-\\mu/L=0.8$, so $100$ error units drop to $80$." },
      { title: "Fixed-point view of updates", background: "An optimum satisfies $\\nabla f(w^*)=0$, so it is a fixed point of $T(w)=w-\\eta\\nabla f(w)$.", numbers: "For $f(w)=(w-3)^2$, $T(w)=w-0.1\\cdot2(w-3)=0.8w+0.6$, whose fixed point is $3$." },
      { title: "Divergence from too-large steps", background: "Oversized learning rates can create expanding oscillations even on easy losses.", numbers: "For $f(w)=5w^2$ and $\\eta=0.25$, multiplier is $-1.5$; magnitudes go $1,1.5,2.25,3.375$." },
      { title: "Stochastic gradient noise", background: "SGD uses noisy gradients, so constant steps often converge to a noise ball rather than the exact minimizer.", numbers: "If gradient noise standard deviation is $0.2$ and step is $0.01$, update noise scale is about $0.002$ per step." },
      { title: "Gradient clipping", background: "Deep learning often controls effective Lipschitz behavior when exact constants are unavailable.", numbers: "Clipping a gradient norm from $50$ to $5$ with step $0.01$ changes update length from $0.5$ to $0.05$." }
    ],
    applicationsClose: "Gradient convergence is not magic: smoothness controls the landscape, curvature identifies the target, and the learning rate decides whether the update contracts or expands.",
    takeaways: ["Gradient descent is fixed-point iteration $w_{k+1}=w_k-\\eta\\nabla f(w_k)$.", "For a quadratic, the error multiplier is $1-\\eta a$ in one dimension.", "Convergence requires the step size to respect curvature, such as $0<\\eta<2/L$ in the quadratic case.", "Strong convexity plus smoothness gives geometric convergence guarantees; noise and nonconvexity require more care."]
  }
};
