/* =====================================================================
   AFP-AI LESSON GENERATOR
   ---------------------------------------------------------------------
   Reads every tools/afp-authored/*.js (each `module.exports = [lessons]`),
   merges + sorts by module number `m`, and emits a single
   lessons/afp-ai.js registering all modules into window.LESSONS with
   template:"afp" + superGroup:"AFP-AI".

   Run:  node tools/gen-afp.js
   ===================================================================== */
"use strict";
const fs = require("fs");
const path = require("path");
const OUT = path.join(__dirname, "..", "lessons");
const SRC = path.join(__dirname, "afp-authored");

/* Domain metadata: the nav-section name (module) and breadcrumb (book) per domain. */
const DOMAINS = {
  0: { module: "Domain 0 · ML Foundations",                        book: "AFP-AI · ML Foundations" },
  1: { module: "Domain 1 · Core: Ranking & Evaluation",            book: "AFP-AI · Ranking & Evaluation" },
  2: { module: "Domain 2 · Recommenders, Embeddings & Retrieval",  book: "AFP-AI · Retrieval & Embeddings" },
  3: { module: "Domain 3 · Unsupervised",                          book: "AFP-AI · Unsupervised" },
  4: { module: "Domain 4 · Applied LLMs / GenAI",                  book: "AFP-AI · Applied LLMs / GenAI" },
  5: { module: "Domain 5 · Bandits & RL",                          book: "AFP-AI · Bandits & RL" },
  6: { module: "Domain 6 · Optimization & Marketplace",            book: "AFP-AI · Optimization & Marketplace" }
};
/* MODULE_ORDER must list the domain sections in this order (0..6). */
const MODULE_ORDER = [0, 1, 2, 3, 4, 5, 6].map(d => DOMAINS[d].module);

const pad = (x) => String(x).padStart(2, "0");
const mid = (m) => `afp-m${pad(m)}`;

/* --- load authored modules ------------------------------------------- */
if (!fs.existsSync(SRC)) throw new Error("tools/afp-authored/ not found");
let mods = [];
fs.readdirSync(SRC).filter(f => /\.js$/.test(f)).sort().forEach(f => {
  const arr = require(path.join(SRC, f));
  if (!Array.isArray(arr)) throw new Error(`${f} must module.exports an array`);
  mods = mods.concat(arr);
});
mods.sort((a, b) => a.m - b.m);

/* --- validate uniqueness / domain --------------------------------------- */
const seen = new Set();
mods.forEach(o => {
  if (o.m == null || o.domain == null) throw new Error(`module missing m/domain: ${JSON.stringify(o.title)}`);
  if (!DOMAINS[o.domain]) throw new Error(`unknown domain ${o.domain} for M${o.m}`);
  if (seen.has(o.m)) throw new Error(`duplicate module number M${o.m}`);
  seen.add(o.m);
});

/* --- build the runtime lesson objects ---------------------------------- */
let prevId = null;
const objs = mods.map(o => {
  const d = DOMAINS[o.domain];
  const data = Object.assign({}, o);
  delete data.notebook;   // notebooks are emitted separately; keep the lesson file lean
  delete data.m;
  delete data.domain;
  const lesson = Object.assign({
    id: mid(o.m),
    module: d.module,
    book: d.book,
    title: `M${o.m} · ${o.title}`
  }, data);
  lesson.title = `M${o.m} · ${o.title}`;
  if (!lesson.prereqs && prevId) lesson.prereqs = [prevId];
  prevId = lesson.id;
  Object.keys(lesson).forEach(k => lesson[k] === undefined && delete lesson[k]);
  return lesson;
});

/* --- emit lessons/afp-ai.js -------------------------------------------- */
const body = objs.map(o => `  B(${JSON.stringify(o, null, 2).replace(/\n/g, "\n  ")});`).join("\n\n");
const file =
  `/* AFP-AI Learning Guide (Param Kulkarni) — interactive track.\n` +
  `   Generated by tools/gen-afp.js from tools/afp-authored/*.js. Do not edit by hand.\n` +
  `   ${objs.length} modules across 7 domains; template:"afp" renders via renderAFP in index.html. */\n` +
  `(function () {\n` +
  `  window.LESSONS = window.LESSONS || [];\n` +
  `  const B = (o) => window.LESSONS.push(Object.assign({ template: "afp", superGroup: "AFP-AI" }, o));\n\n` +
  body + `\n})();\n`;
fs.writeFileSync(path.join(OUT, "afp-ai.js"), file);

/* --- wiring snippets ---------------------------------------------------- */
fs.writeFileSync(path.join(__dirname, "afp-order.snippet.txt"),
  MODULE_ORDER.map(n => `    ${JSON.stringify(n)},`).join("\n") + "\n");
fs.writeFileSync(path.join(__dirname, "afp-includes.snippet.html"),
  `<!-- AFP-AI Learning Guide — generated track -->\n<script src="lessons/afp-ai.js"></script>\n`);

console.log(`Wrote lessons/afp-ai.js — ${objs.length} modules (M${mods[0] ? mods[0].m : "?"}..M${mods.length ? mods[mods.length - 1].m : "?"}).`);
console.log("Domains present:", [...new Set(mods.map(m => m.domain))].sort().join(", "));
